// Generated by rowstile client from the policy. Do not edit; re-run after changing the policy.
// The policy's names, for the SDK (@rowstile/client): a misspelled type or permission doesn't type-check.
import type {} from "@rowstile/client";

export const permissions = {
  "project": [
    "edit",
    "view",
    "share"
  ],
  "note": [
    "edit",
    "view"
  ],
  "message": [
    "read"
  ]
} as const;
export type ObjectType = keyof typeof permissions;
export type Permission<T extends ObjectType> = (typeof permissions)[T][number];

/** Relations people may share, and with whom (subject type, or type#relation). */
export const sharedRelations = {
  "project": {
    "viewer": [
      "user"
    ]
  }
} as const;

export const scopes = [] as const;
export type Scope = (typeof scopes)[number];

declare module "@rowstile/client" {
  interface Register {
    permissions: typeof permissions;
    sharedRelations: typeof sharedRelations;
  }
}
