"""Developer tools: a diagram of the policy (Mermaid) and typed client helpers (TypeScript, Python)."""

from __future__ import annotations

import json
import re
from collections.abc import Callable
from typing import TypeAlias

from .compiler import Core
from .parse import Expr, Perm, Type

# what the clients are made from: {type: [permission]}, {type: {relation: [subject]}}, [scope]
Perms: TypeAlias = "dict[str, list[str]]"
Shared: TypeAlias = "dict[str, dict[str, list[str]]]"


def _id(*parts: str) -> str:
    """A node's id in the diagram: a type's name and a relation's or permission's, joined by the one thing a name
    can't hold (`__`), so two of them never share an id (`team` + `member_view`, `team_member` + `view`)."""
    return "__".join(re.sub(r"[^A-Za-z0-9_]", "_", p) for p in parts)


def _box(type_name: str) -> str:
    """The id of a type's box: no relation or permission is named `0` (a name doesn't start with a digit)."""
    return _id(type_name, "0")


def _special(name: str) -> str:
    """The id of the `anyone` and `link` circles."""
    return _id(name, "1")


def _label(text: str) -> str:
    return text.replace('"', "'")


class DevMixin(Core):
    # ------------------------------------------------------------------
    # diagram
    # ------------------------------------------------------------------
    def graph(self) -> str:
        """A Mermaid flowchart: types, their relations (boxes) and permissions (rounded),
        what each permission is made of, and where relations point."""
        out = [
            "%% Generated by rowstile graph. Paste into any Mermaid viewer (GitHub renders it in ```mermaid blocks).",
            "flowchart LR",
            "  classDef perm fill:#e8f0fe,stroke:#4a6fd1,color:#1b2a4a",
            "  classDef rel fill:#f6f6f6,stroke:#888,color:#222",
            "  classDef user fill:#fff4e0,stroke:#d19a4a,color:#4a2f0b",
        ]
        edges: list[str] = []
        specials: set[str] = set()
        user_node = "user" if "user" in self.types else None
        for t in self.types.values():
            if t.name == "user" and not t.perms:
                out.append('  user(("user")):::user')
                continue
            out.append(f'  subgraph {_box(t.name)}["{_label(t.name)} · {_label(t.table)}"]')
            if t.name == "user":
                out.append('    user(("user")):::user')
            for r in t.relations.values():
                label = f"custom roles → {r.sources[0].perm}" if r.synthetic else r.name
                out.append(f'    {_id(t.name, r.name)}["{_label(label)}"]:::rel')
                for src in r.sources:
                    col = src.column if isinstance(src.column, str) else "[" + ", ".join(src.column or ()) + "]"
                    how = {"shared": "shared", "roles": "roles", "table": src.table or "", "column": col or ""}[
                        src.kind
                    ]
                    if src.kind == "column" and src.type_col:
                        how = f"({src.type_col}, {col})"
                    for st, sr in src.subjects:
                        drawn = st in self.types and (st != "user" or bool(self.types[st].perms))  # its box is there
                        if st in ("anyone", "link"):
                            target = _special(st)
                            specials.add(st)
                            lab = how
                        elif sr == "*":
                            # everyone of the type who is signed in: the user, or the type's box
                            target = user_node if st == "user" else _box(st)
                            lab = how + (" (everyone)" if st == "user" else f" (every {st})")
                        elif sr and drawn:
                            target = _id(st, sr)
                            lab = how
                        elif st == "user":
                            target = user_node
                            lab = how
                        else:
                            target = _box(st)
                            lab = how
                        style = "-.->" if src.kind in ("shared", "roles") else "-->"
                        edges.append(f'  {_id(t.name, r.name)} {style}|"{_label(lab)}"| {target}')
            for p in t.perms.values():
                label = p.name.replace("__base", ", before the deny") if p.hidden else p.name
                out.append(f'    {_id(t.name, p.name)}(["{_label(label)}"]):::perm')
                self._graph_expr(t, p, p.expr, edges, negated=False, cond=False)
            out.append("  end")
        out += [f'  {_special(st)}(("{st}")):::user' for st in sorted(specials)]
        return "\n".join(out + list(dict.fromkeys(edges))) + "\n"

    def _graph_expr(self, t: Type, p: Perm, node: Expr, edges: list[str], negated: bool, cond: bool) -> None:
        src = _id(t.name, p.name)

        def is_cond(n: Expr) -> bool:
            match n:
                case ("cond", _):
                    return True
                case ("not", inner):
                    return is_cond(inner)
            return False

        match node:
            case ("or", items) | ("and", items):
                has_cond = cond or (node[0] == "and" and any(is_cond(n) for n in items))
                for n in items:
                    self._graph_expr(t, p, n, edges, negated, has_cond)
            case ("not", inner):
                self._graph_expr(t, p, inner, edges, not negated, cond)
            case ("ref", name):
                lab = ("not" if negated else "") + (" if {…}" if cond else "")
                arrow = f'-.->|"{lab.strip()}"|' if lab else "-->"
                edges.append(f"  {src} {arrow} {_id(t.name, name)}")
            case ("arrow", rel, perm):
                r = t.relations.get(rel)
                targets = [st for st, sr in r.subjects() if not sr] if r else []
                lab = rel + (" · not" if negated else "") + (" · if {…}" if cond else "")
                for st in targets:
                    edges.append(f'  {src} ==>|"{_label(lab)}"| {_id(st, perm)}')

    # ------------------------------------------------------------------
    # client helpers
    # ------------------------------------------------------------------
    def _client_model(self) -> tuple[Perms, Shared, list[str]]:
        perms = {t.name: self.public_perms(t) for t in self.types.values() if self.public_perms(t)}
        shared: Shared = {}
        for t in self.types.values():
            for r in t.relations.values():
                for src in r.sources:
                    if src.kind == "shared":
                        subs = shared.setdefault(t.name, {}).setdefault(r.name, [])
                        for st, sr in src.subjects:
                            key = f"{st}:*" if sr == "*" else (f"{st}#{sr}" if sr else st)
                            if key not in subs:
                                subs.append(key)
        scopes = list(self.pol.scopes)
        return perms, shared, scopes

    def client(self, lang: str, source_name: str) -> str:
        perms, shared, scopes = self._client_model()
        if lang in ("ts", "typescript"):
            return self._client_ts(perms, shared, scopes, source_name)
        if lang == "ts-sdk":
            return self._client_ts_names(perms, shared, scopes, source_name)
        if lang in ("py", "python"):
            return self._client_py(perms, shared, scopes, source_name)
        raise ValueError(f"unknown client language '{lang}' (use py or ts; ts-sdk for the names alone)")

    def _client_ts(self, perms: Perms, shared: Shared, scopes: list[str], source_name: str) -> str:
        j: Callable[[object], str] = lambda x: json.dumps(x, indent=2)
        return f"""// Generated by rowstile client from {source_name}. Do not edit; re-run after changing the policy.
export const permissions = {j(perms)} as const;
export type ObjectType = keyof typeof permissions;
export type Permission<T extends ObjectType> = (typeof permissions)[T][number];

/** Relations people may share with authz.share(), and with whom (subject type, or type#relation). */
export const sharedRelations = {j(shared)} as const;
export type SharedType = keyof typeof sharedRelations;
export type SharedRelation<T extends SharedType> = keyof (typeof sharedRelations)[T] & string;

export const scopes = {j(scopes)} as const;
export type Scope = (typeof scopes)[number];

/** Anything with query(text, params) -> {{ rows }}: a pg Client, PoolClient, or similar. */
export interface Queryable {{
  query(text: string, params?: unknown[]): Promise<{{ rows: any[] }}>;
}}
/** An object's id; for a composite key, its columns in order: [orgId, id]. */
export type Id = string | number | bigint | readonly (string | number | bigint)[];
// a composite key as Postgres writes a row: every field quoted, quotes and backslashes escaped
const s = (id: Id): string => Array.isArray(id)
  ? "(" + id.map((v) => '"' + String(v).replace(/["\\\\]/g, (c) => "\\\\" + c) + '"').join(",") + ")"
  : String(id);

/** A key as the database writes it, for a message: 7, or (1,2) for a key of several columns. */
const shown = (id: Id): string => Array.isArray(id)
  ? "(" + id.map((v) => /^$|[",\\\\()\\s]/.test(String(v)) ? '"' + String(v).replace(/\\\\/g, "\\\\\\\\").replace(/"/g, '""') + '"' : String(v)).join(",") + ")"
  : String(id);
// who is signed in, in the words the database's own refusals use
const WHO = "SELECT coalesce((SELECT p.principal_type || ' ' || p.principal_id FROM authz.principal() p), 'someone not signed in') AS who";

/** The database refused a write (SQLSTATE 42501): its message, the table and command, and why (lines). */
export class Refused extends Error {{
  constructor(message: string, public table?: string, public command?: string, public why: string[] = []) {{ super(message); }}
}}
/** The row isn't there, or the signed-in user can't see it. */
export class NotFound extends Error {{
  constructor(public table: string, public id: string) {{ super(`${{table}} ${{id}} not found`); }}
}}
/** A Refused for a database error that is a refusal (from pg: code, detail, schema, table, constraint), else null. */
export function refusal(e: any): Refused | null {{
  if (!e || e.code !== "42501") return null;
  const constraint = String(e.constraint ?? "");
  return new Refused(String(e.message), e.schema && e.table ? `${{e.schema}}.${{e.table}}` : e.table,
    constraint.startsWith("authz_") ? constraint.slice(6) : undefined, e.detail ? String(e.detail).split("\\n") : []);
}}

/** Runs fn in a transaction signed in as userId (authz.act_as); rows are filtered by RLS. */
export async function asUser<R>(db: Queryable, userId: Id | null, fn: (db: Queryable) => Promise<R>): Promise<R> {{
  await db.query("BEGIN");
  try {{
    await db.query("SELECT authz.act_as('user', $1)", [userId === null ? null : s(userId)]);
    const out = await fn(db);
    await db.query("COMMIT");
    return out;
  }} catch (e) {{
    await db.query("ROLLBACK");
    throw e;
  }}
}}

/** The same for a principal other than a user (a service). */
export async function asPrincipal<R>(db: Queryable, principalType: string, id: Id, fn: (db: Queryable) => Promise<R>): Promise<R> {{
  await db.query("BEGIN");
  try {{
    await db.query("SELECT authz.act_as($1, $2)", [principalType, s(id)]);
    const out = await fn(db);
    await db.query("COMMIT");
    return out;
  }} catch (e) {{
    await db.query("ROLLBACK");
    throw e;
  }}
}}

/** Typed wrappers for the authz.* SQL API; call them inside asUser (or after authz.login_key/login_jwt). */
export function authz(db: Queryable) {{
  return {{
    can: async <T extends ObjectType>(type: T, id: Id, perm: Permission<T>): Promise<boolean> =>
      (await db.query("SELECT authz.can($1, $2::text, $3) AS ok", [type, s(id), perm])).rows[0].ok,
    /** What is wrong with this connection: call it when the app starts, and refuse to start on an 'error'. */
    connectionCheck: async (): Promise<{{ severity: string; problem: string }}[]> =>
      (await db.query("SELECT severity, problem FROM authz.connection_check()", [])).rows,
    /** Every id the user holds perm on; with limit, a page in key order after `after`. */
    list: async <T extends ObjectType>(type: T, perm: Permission<T>, page: {{ after?: Id; limit?: number }} = {{}}): Promise<string[]> =>
      (await db.query("SELECT x FROM authz.list($1, $2, $3, $4) x",
        [type, perm, page.after === undefined ? null : s(page.after), page.limit ?? null])).rows.map((r) => r.x),
    perms: async <T extends ObjectType>(type: T, id: Id): Promise<Permission<T>[]> =>
      (await db.query("SELECT authz.perms($1, $2::text) AS p", [type, s(id)])).rows[0].p ?? [],
    who: async <T extends ObjectType>(type: T, id: Id, perm: Permission<T>): Promise<string[]> =>
      (await db.query("SELECT x FROM authz.who($1, $2::text, $3) x", [type, s(id), perm])).rows.map((r) => r.x),
    explain: async <T extends ObjectType>(type: T, id: Id, perm: Permission<T>, user?: Id): Promise<string[]> =>
      (await db.query("SELECT e FROM authz.explain($1, $2::text, $3, $4) e", [type, s(id), perm, user === undefined ? null : s(user)])).rows.map((r) => r.e),
    share: async <T extends SharedType>(type: T, id: Id, relation: SharedRelation<T>, subjectType: string, subjectId: Id,
                                        opts: {{ subjectRelation?: string; expiresAt?: Date; startsAt?: Date; caveat?: string; caveatArgs?: object }} = {{}}) =>
      db.query("SELECT authz.share($1, $2::text, $3, $4, $5::text, $6, $7, $8, $9, $10)",
        [type, s(id), relation, subjectType, s(subjectId), opts.subjectRelation ?? "", opts.expiresAt ?? null, opts.startsAt ?? null,
         opts.caveat ?? null, opts.caveatArgs ? JSON.stringify(opts.caveatArgs) : null]),
    unshare: async <T extends SharedType>(type: T, id: Id, relation: SharedRelation<T>, subjectType: string, subjectId: Id, subjectRelation = "") =>
      db.query("SELECT authz.unshare($1, $2::text, $3, $4, $5::text, $6)", [type, s(id), relation, subjectType, s(subjectId), subjectRelation]),
    requestAccess: async <T extends SharedType>(type: T, id: Id, relation: SharedRelation<T>, reason: string, duration?: string): Promise<string> =>
      (await db.query("SELECT authz.request_access($1, $2::text, $3, $4, $5::interval) AS id", [type, s(id), relation, reason, duration ?? null])).rows[0].id,
    decideRequest: async (requestId: Id, approve: boolean, note?: string) =>
      db.query("SELECT authz.decide_request($1::bigint, $2, $3)", [s(requestId), approve, note ?? null]),
    /** A share with anyone holding the returned token (shown once; only its hash is stored). */
    createLink: async <T extends SharedType>(type: T, id: Id, relation: SharedRelation<T>, expiresAt?: Date): Promise<string> =>
      (await db.query("SELECT authz.create_link($1, $2::text, $3, $4) AS token", [type, s(id), relation, expiresAt ?? null])).rows[0].token,
    /** The links on an object (id, relation, created_by, created_at, expires_at), for those who can share it or may
     *  make such links. */
    listLinks: async <T extends ObjectType>(type: T, id: Id): Promise<any[]> =>
      (await db.query("SELECT * FROM authz.list_links($1, $2::text)", [type, s(id)])).rows,
    /** Turns a link off, by its id in listLinks (not its token). */
    revokeLink: async <T extends ObjectType>(type: T, id: Id, linkId: string) =>
      db.query("SELECT authz.revoke_link($1, $2::text, $3)", [type, s(id), linkId]),
    /** Link tokens the request presents, for this transaction. */
    useLinks: async (tokens: string[]) => db.query("SELECT set_config('authz_ctx.links', $1, true)", [tokens.join(",")]),
    cancelRequest: async (requestId: Id) => db.query("SELECT authz.cancel_request($1::bigint)", [s(requestId)]),
    pendingRequests: async (): Promise<any[]> => (await db.query("SELECT * FROM authz.pending_requests()")).rows,
    listShares: async <T extends ObjectType>(type: T, id: Id): Promise<any[]> =>
      (await db.query("SELECT * FROM authz.list_shares($1, $2::text)", [type, s(id)])).rows,
    breakGlass: async <T extends SharedType>(type: T, id: Id, relation: SharedRelation<T>, reason: string, duration = "1 hour") =>
      db.query("SELECT authz.break_glass($1, $2::text, $3, $4, $5::interval)", [type, s(id), relation, reason, duration]),
    startReview: async <T extends ObjectType>(type: T, id: Id, closesAt?: Date): Promise<string> =>
      (await db.query("SELECT authz.start_review($1, $2::text, coalesce($3::timestamptz, now() + interval '14 days')) AS id",
        [type, s(id), closesAt ?? null])).rows[0].id,
    reviewItems: async (reviewId: Id): Promise<any[]> => (await db.query("SELECT * FROM authz.review_items($1::bigint)", [s(reviewId)])).rows,
    reviewDecide: async (reviewId: Id, item: number, keep: boolean) =>
      db.query("SELECT authz.review_decide($1::bigint, $2, $3)", [s(reviewId), item, keep]),
    closeReview: async (reviewId: Id, revokeUndecided = false): Promise<number> =>
      (await db.query("SELECT authz.close_review($1::bigint, $2) AS n", [s(reviewId), revokeUndecided])).rows[0].n,
    loginKey: async (key: string) => db.query("SELECT authz.login_key($1)", [key]),
    loginJwt: async (token: string) => db.query("SELECT authz.login_jwt($1)", [token]),
    /** A key for yourself, or (holding manage_keys on it) for a principal such as a service. Shown once. */
    createApiKey: async (name: string, opts: {{ scopes?: string; expiresAt?: Date; principalType?: string; principalId?: Id }} = {{}}): Promise<string> =>
      (await db.query("SELECT authz.create_api_key($1, $2, $3, $4, $5) AS key",
        [name, opts.scopes ?? "", opts.expiresAt ?? null, opts.principalType ?? null,
         opts.principalId === undefined ? null : s(opts.principalId)])).rows[0].key,
    listApiKeys: async (principalType?: string, principalId?: Id): Promise<any[]> =>
      (await db.query("SELECT * FROM authz.list_api_keys($1, $2)", [principalType ?? null, principalId === undefined ? null : s(principalId)])).rows,
    revokeApiKey: async (keyId: Id) => db.query("SELECT authz.revoke_api_key($1::bigint)", [s(keyId)]),
    /** Why a write is or would be refused: an insert (row: the new row), or an update or delete of the row with this
     *  id (for an update, row: the new values). null: that row isn't there, or you can't see it. */
    explainRule: async (table: string, command: "insert" | "update" | "delete", id?: Id, row?: object): Promise<string[] | null> =>
      (await db.query("SELECT authz.explain_rule($1, $2, $3, $4::jsonb) AS e",
        [table, command, id === undefined ? null : s(id), row === undefined ? null : JSON.stringify(row)])).rows[0].e,
    /** The result of an UPDATE or DELETE (rows, a count, or what the driver gave: its rowCount or rows): returned
     *  if anything changed, otherwise NotFound (you can't see the row) or Refused (you may not, and why). */
    expect: async <R>(result: R, table: string, command: "update" | "delete", id: Id, row?: object): Promise<R> => {{
      const given: any = result;
      const changed = Array.isArray(given) ? given.length > 0 : typeof given === "number" ? given > 0
        : given && typeof given.rowCount === "number" ? given.rowCount > 0
        : given && Array.isArray(given.rows) ? given.rows.length > 0 : Boolean(given);
      if (changed) return result;
      const why: string[] | null = (await db.query("SELECT authz.explain_rule($1, $2, $3, $4::jsonb) AS e",
        [table, command, s(id), row === undefined ? null : JSON.stringify(row)])).rows[0].e;
      // nothing there for this user, or the rule allows it (its first line says yes) and the statement matched
      // nothing for another reason, such as a WHERE with more than the key
      if (why === null || /^\\s*yes\\b/.test(why[0] ?? "")) throw new NotFound(table, shown(id));
      const who: string = (await db.query(WHO)).rows[0].who;
      throw new Refused(`permission denied: ${{who}} may not ${{command}} row ${{shown(id)}} of ${{table}}`, table, command, why);
    }},
    /** Which of these people (or principals of another type) hold perm: one call, for live updates. Signs each one
     *  in, so it needs what signing in needs (SET on authz.user_id). */
    whoAmong: async <T extends ObjectType>(type: T, id: Id, perm: Permission<T>, principals: Id[], principalType = "user"): Promise<string[]> =>
      (await db.query("SELECT x FROM authz.who_among($1, $2::text, $3, $4::text[], $5) x",
        [type, s(id), perm, principals.map(s), principalType])).rows.map((r) => r.x),
  }};
}}
"""

    def _client_ts_names(self, perms: Perms, shared: Shared, scopes: list[str], source_name: str) -> str:
        """For apps on the TypeScript SDK (@rowstile/*): only the policy's names, registered with the SDK, so
        its functions take only the types and permissions the policy declares."""
        j: Callable[[object], str] = lambda x: json.dumps(x, indent=2)
        return f"""// Generated by rowstile client from {source_name}. Do not edit; re-run after changing the policy.
// The policy's names, for the SDK (@rowstile/client): a misspelled type or permission doesn't type-check.
import type {{}} from "@rowstile/client";

export const permissions = {j(perms)} as const;
export type ObjectType = keyof typeof permissions;
export type Permission<T extends ObjectType> = (typeof permissions)[T][number];

/** Relations people may share, and with whom (subject type, or type#relation). */
export const sharedRelations = {j(shared)} as const;

export const scopes = {j(scopes)} as const;
export type Scope = (typeof scopes)[number];

declare module "@rowstile/client" {{
  interface Register {{
    permissions: typeof permissions;
    sharedRelations: typeof sharedRelations;
  }}
}}
"""

    def _client_py(self, perms: Perms, shared: Shared, scopes: list[str], source_name: str) -> str:
        lit_union: Callable[[list[str]], str] = lambda xs: (
            "Literal[" + ", ".join(json.dumps(x) for x in xs) + "]" if xs else "str"
        )
        all_perms = sorted({p for ps in perms.values() for p in ps})
        per_type = "\n".join(f"{_id(t).capitalize()}Permission = {lit_union(ps)}" for t, ps in perms.items())
        return f'''"""Generated by rowstile client from {source_name}. Do not edit; re-run after changing the policy.

Works with any DB-API connection using %s placeholders (psycopg, psycopg2):

    with conn.transaction():                     # psycopg 3; or: BEGIN ... COMMIT
        Authz(conn).sign_in(7)                   # SELECT authz.act_as('user', '7')
        if Authz(conn).can("file", 11, "edit"): ...
"""
from __future__ import annotations

import datetime
import json
import uuid
from collections.abc import Sequence
from types import TracebackType
from typing import TYPE_CHECKING, Literal, Protocol, TypeVar

if TYPE_CHECKING:
    from typing import LiteralString  # Python 3.11

PERMISSIONS: dict[str, list[str]] = {json.dumps(perms, indent=4)}
SHARED_RELATIONS: dict[str, dict[str, list[str]]] = {json.dumps(shared, indent=4)}
SCOPES: list[str] = {json.dumps(scopes)}

ObjectType = {lit_union(list(perms))}
Permission = {lit_union(all_perms)}
{per_type}
# an object's id; for a composite key, its columns in order: (org_id, id)
Id = int | str | uuid.UUID | tuple[int | str | uuid.UUID, ...]
When = datetime.datetime | str                  # a timestamptz: a datetime, or text Postgres reads
Row = dict[str, object]
Result = TypeVar("Result")


class Cursor(Protocol):
    """What the client uses of a DB-API cursor (psycopg's, psycopg2's)."""
    @property
    def description(self) -> Sequence[Sequence[object]] | None: ...
    def execute(self, query: LiteralString, params: Sequence[object], /) -> object: ...
    def fetchone(self) -> Sequence[object] | None: ...
    def fetchall(self) -> Sequence[Sequence[object]]: ...
    def __enter__(self) -> Cursor: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None,
                 tb: TracebackType | None, /) -> object: ...


class Connection(Protocol):
    def cursor(self) -> Cursor: ...


def _texts(value: object) -> list[str]:
    """A text[] from the database (None: none)."""
    return [str(x) for x in value] if isinstance(value, (list, tuple)) else []


def _int(value: object) -> int:
    if isinstance(value, (int, str)):
        return int(value)
    raise TypeError(f"expected a number from the database, got {{value!r}}")


def _id(x: Id) -> str:
    """A composite key as Postgres writes a row: every field quoted, quotes and backslashes escaped."""
    if isinstance(x, (tuple, list)):
        return "(" + ",".join('"' + str(v).replace("\\\\", "\\\\\\\\").replace('"', '\\\\"') + '"' for v in x) + ")"
    return str(x)


def _shown(x: Id) -> str:
    """A key as the database writes it, for a message: 7, or (1,2) for a key of several columns."""
    if not isinstance(x, (tuple, list)):
        return str(x)

    def field(v: object) -> str:
        s = str(v)
        if s == "" or any(ch in s for ch in '",\\\\()') or any(ch.isspace() for ch in s):
            return '"' + s.replace("\\\\", "\\\\\\\\").replace('"', '""') + '"'
        return s

    return "(" + ",".join(field(v) for v in x) + ")"


# who is signed in, in the words the database's own refusals use
_WHO = "SELECT coalesce((SELECT p.principal_type || ' ' || p.principal_id FROM authz.principal() p), 'someone not signed in')"


class Refused(Exception):
    """The database refused a write (SQLSTATE 42501): its message, the table and command, and why (lines)."""

    def __init__(self, message: str, table: str | None = None, command: str | None = None, why: Sequence[str] = ()) -> None:
        super().__init__(message)
        self.message, self.table, self.command, self.why = message, table, command, list(why)


class NotFound(Exception):
    """The row isn't there, or the signed-in user can't see it."""

    def __init__(self, table: str, id_: str) -> None:
        super().__init__(f"{{table}} {{id_}} not found")
        self.table, self.id = table, id_


def refusal(error: BaseException) -> Refused | None:
    """A Refused for a database error that is a refusal, else None (psycopg, psycopg2)."""
    if (getattr(error, "sqlstate", None) or getattr(error, "pgcode", None)) != "42501":
        return None
    diag = getattr(error, "diag", None)
    message = getattr(diag, "message_primary", None) or str(error).split("\\n")[0]
    detail = getattr(diag, "message_detail", None) or ""
    schema, table = getattr(diag, "schema_name", None), getattr(diag, "table_name", None)
    constraint = getattr(diag, "constraint_name", None) or ""
    return Refused(message, f"{{schema}}.{{table}}" if schema and table else table,
                   constraint[6:] if constraint.startswith("authz_") else None, detail.split("\\n") if detail else [])


class Authz:
    def __init__(self, conn: Connection) -> None:
        self.conn = conn

    def _one(self, sql: LiteralString, args: Sequence[object]) -> object:
        with self.conn.cursor() as cur:
            cur.execute(sql, args)
            row = cur.fetchone()
            return row[0] if row else None

    def _all(self, sql: LiteralString, args: Sequence[object]) -> Sequence[str]:
        with self.conn.cursor() as cur:
            cur.execute(sql, args)
            return [str(r[0]) for r in cur.fetchall()]

    def _rows(self, sql: LiteralString, args: Sequence[object]) -> Sequence[Row]:
        with self.conn.cursor() as cur:
            cur.execute(sql, args)
            names = [str(d[0]) for d in cur.description or []]
            return [dict(zip(names, r, strict=True)) for r in cur.fetchall()]

    @staticmethod
    def _check(type_: str, perm: str) -> None:
        if type_ not in PERMISSIONS or perm not in PERMISSIONS[type_]:
            raise ValueError(f"{{type_}} has no permission {{perm!r}} in the policy")

    def sign_in(self, user_id: Id | None) -> None:
        """For this transaction only (run inside a transaction); None: nobody. A signed session (authz.act_as)."""
        self._one("SELECT authz.act_as('user', %s)", (None if user_id is None else _id(user_id),))

    def sign_in_as(self, principal_type: str, principal_id: Id) -> None:
        """A principal other than a user (a service), for this transaction only."""
        self._one("SELECT authz.act_as(%s, %s)", (principal_type, _id(principal_id)))

    def connection_check(self) -> Sequence[Row]:
        """What is wrong with this connection, as rows of severity and problem: call it when the app starts, and
        refuse to start on an 'error' (a role row-level security doesn't apply to, or one the policy doesn't govern)."""
        return self._rows("SELECT severity, problem FROM authz.connection_check()", ())

    def principal(self) -> tuple[str, str] | None:
        """(type, id) of whoever is signed in, or None."""
        rows = self._all("SELECT principal_type || ':' || principal_id FROM authz.principal()", ())
        if not rows:
            return None
        kind, _, pid = rows[0].partition(":")
        return kind, pid

    def login_key(self, key: str) -> None:
        self._one("SELECT authz.login_key(%s)", (key,))

    def login_jwt(self, token: str) -> None:
        self._one("SELECT authz.login_jwt(%s)", (token,))

    def create_api_key(self, name: str, scopes: str = "", expires_at: When | None = None, principal_type: str | None = None,
                       principal_id: Id | None = None) -> str:
        """A key for yourself, or (holding manage_keys on it) for a principal such as a service. Shown once."""
        return str(self._one("SELECT authz.create_api_key(%s, %s, %s, %s, %s)",
                             (name, scopes, expires_at, principal_type, None if principal_id is None else _id(principal_id))))

    def list_api_keys(self, principal_type: str | None = None, principal_id: Id | None = None) -> Sequence[Row]:
        return self._rows("SELECT * FROM authz.list_api_keys(%s, %s)",
                          (principal_type, None if principal_id is None else _id(principal_id)))

    def revoke_api_key(self, key_id: int) -> None:
        self._one("SELECT authz.revoke_api_key(%s)", (key_id,))

    def can(self, type_: ObjectType, id_: Id, perm: Permission) -> bool:
        self._check(type_, perm)
        return bool(self._one("SELECT authz.can(%s, %s::text, %s)", (type_, _id(id_), perm)))

    def list(self, type_: ObjectType, perm: Permission, after: Id | None = None,
             limit: int | None = None) -> Sequence[str]:
        """Every id the user holds perm on; with limit, a page in key order after `after`."""
        self._check(type_, perm)
        return self._all("SELECT x FROM authz.list(%s, %s, %s, %s) x",
                         (type_, perm, None if after is None else _id(after), limit))

    def perms(self, type_: ObjectType, id_: Id) -> Sequence[str]:
        return _texts(self._one("SELECT authz.perms(%s, %s::text)", (type_, _id(id_))))

    def who(self, type_: ObjectType, id_: Id, perm: Permission) -> Sequence[str]:
        self._check(type_, perm)
        return self._all("SELECT x FROM authz.who(%s, %s::text, %s) x", (type_, _id(id_), perm))

    def explain(self, type_: ObjectType, id_: Id, perm: Permission, user: Id | None = None) -> Sequence[str]:
        return self._all("SELECT e FROM authz.explain(%s, %s::text, %s, %s) e",
                         (type_, _id(id_), perm, None if user is None else _id(user)))

    def share(self, type_: str, id_: Id, relation: str, subject_type: str, subject_id: Id, subject_relation: str = "",
              expires_at: When | None = None, starts_at: When | None = None, caveat: str | None = None,
              caveat_args: str | None = None) -> None:
        if relation not in SHARED_RELATIONS.get(type_, {{}}):
            raise ValueError(f"{{type_}}.{{relation}} is not shared in the policy")
        self._one("SELECT authz.share(%s, %s::text, %s, %s, %s::text, %s, %s, %s, %s, %s::jsonb)",
                  (type_, _id(id_), relation, subject_type, _id(subject_id), subject_relation, expires_at, starts_at,
                   caveat, caveat_args))

    def create_link(self, type_: str, id_: Id, relation: str, expires_at: When | None = None) -> str:
        """A share with anyone holding the returned token (shown once; only its hash is stored)."""
        if relation not in SHARED_RELATIONS.get(type_, {{}}):
            raise ValueError(f"{{type_}}.{{relation}} is not shared in the policy")
        return str(self._one("SELECT authz.create_link(%s, %s::text, %s, %s)", (type_, _id(id_), relation, expires_at)))

    def list_links(self, type_: ObjectType, id_: Id) -> Sequence[Row]:
        """The links on an object (id, relation, created_by, created_at, expires_at), for those who can share it
        or may make such links."""
        return self._rows("SELECT * FROM authz.list_links(%s, %s::text)", (type_, _id(id_)))

    def revoke_link(self, type_: ObjectType, id_: Id, link_id: str) -> None:
        """Turns a link off, by its id in list_links (not its token)."""
        self._one("SELECT authz.revoke_link(%s, %s::text, %s)", (type_, _id(id_), link_id))

    def use_links(self, tokens: Sequence[str]) -> None:
        """Link tokens the request presents, for this transaction (SET LOCAL authz_ctx.links)."""
        self._one("SELECT set_config('authz_ctx.links', %s, true)", (",".join(tokens),))

    def unshare(self, type_: str, id_: Id, relation: str, subject_type: str, subject_id: Id, subject_relation: str = "") -> None:
        self._one("SELECT authz.unshare(%s, %s::text, %s, %s, %s::text, %s)",
                  (type_, _id(id_), relation, subject_type, _id(subject_id), subject_relation))

    def request_access(self, type_: str, id_: Id, relation: str, reason: str, duration: str | None = None) -> int:
        return _int(self._one("SELECT authz.request_access(%s, %s::text, %s, %s, %s::interval)",
                              (type_, _id(id_), relation, reason, duration)))

    def decide_request(self, request_id: int, approve: bool, note: str | None = None) -> None:
        self._one("SELECT authz.decide_request(%s, %s, %s)", (request_id, approve, note))

    def cancel_request(self, request_id: int) -> None:
        self._one("SELECT authz.cancel_request(%s)", (request_id,))

    def pending_requests(self) -> Sequence[Row]:
        """Requests the user may decide, and their own (mine = true)."""
        return self._rows("SELECT * FROM authz.pending_requests()", ())

    def list_shares(self, type_: ObjectType, id_: Id) -> Sequence[Row]:
        """The shares on an object, for a sharing dialog."""
        return self._rows("SELECT * FROM authz.list_shares(%s, %s::text)", (type_, _id(id_)))

    def break_glass(self, type_: str, id_: Id, relation: str, reason: str, duration: str = "1 hour") -> None:
        self._one("SELECT authz.break_glass(%s, %s::text, %s, %s, %s::interval)", (type_, _id(id_), relation, reason, duration))

    def start_review(self, type_: ObjectType, id_: Id, closes_at: When | None = None) -> int:
        return _int(self._one("SELECT authz.start_review(%s, %s::text, coalesce(%s::timestamptz, now() + interval '14 days'))",
                              (type_, _id(id_), closes_at)))

    def review_items(self, review_id: int) -> Sequence[Row]:
        return self._rows("SELECT * FROM authz.review_items(%s)", (review_id,))

    def review_decide(self, review_id: int, item: int, keep: bool) -> None:
        self._one("SELECT authz.review_decide(%s, %s, %s)", (review_id, item, keep))

    def close_review(self, review_id: int, revoke_undecided: bool = False) -> int:
        return _int(self._one("SELECT authz.close_review(%s, %s)", (review_id, revoke_undecided)))

    def explain_rule(self, table: str, command: str, id_: Id | None = None, row: Row | None = None) -> Sequence[str] | None:
        """Why a write is or would be refused: an insert (row: the new row), or an update or delete of the row with
        this id (for an update, row: the new values). None: that row isn't there, or you can't see it."""
        lines = self._one("SELECT authz.explain_rule(%s, %s, %s, %s::jsonb)",
                          (table, command, None if id_ is None else _id(id_),
                           None if row is None else json.dumps(row, default=str)))
        return None if lines is None else _texts(lines)

    def expect(self, result: Result, table: str, command: str, id_: Id, row: Row | None = None) -> Result:
        """The result of an UPDATE or DELETE (a row, rows, a count, or the cursor that ran it: its rowcount):
        returned if anything changed, otherwise NotFound (you can't see the row, or the rule allows the write and
        the statement matched nothing for another reason) or Refused (you may not, and why)."""
        count = getattr(result, "rowcount", None)
        if count > 0 if isinstance(count, int) and not isinstance(count, bool) else bool(result):
            return result
        why = self.explain_rule(table, command, id_, row)
        if why is None or (why and why[0].lstrip().startswith("yes")):
            raise NotFound(table, _shown(id_))
        who = self._one(_WHO, ())
        raise Refused(f"permission denied: {{who}} may not {{command}} row {{_shown(id_)}} of {{table}}", table, command, why)

    @staticmethod
    def refusal(error: BaseException) -> Refused | None:
        return refusal(error)

    def who_among(self, type_: ObjectType, id_: Id, perm: Permission, principals: Sequence[Id],
                  principal_type: str = "user") -> Sequence[str]:
        """Which of these people (or principals of another type) hold perm: one call, for live updates. Signs each
        one in, so it needs what signing in needs (SET on authz.user_id)."""
        self._check(type_, perm)
        return self._all("SELECT x FROM authz.who_among(%s, %s::text, %s, %s::text[], %s) x",
                         (type_, _id(id_), perm, [_id(p) for p in principals], principal_type))
'''
