"""Policy changes as migrations.

A migration takes a database from the policy the lock file recorded to the policy now. The compiled
policy is read back as objects (statements.py): each function, view, trigger, row-level security
policy and table, with a hash of its SQL. The lock file (authz/policy.lock, committed next to the
migrations) lists them, one sorted line each, after the policy's own lines. So the next migration holds
only what changed:

- a function whose arguments and result are the same: CREATE OR REPLACE, in place
- a view that changed, or reads something that is made again: emptied in place first (the same columns, reading
  nothing), then defined again with CREATE OR REPLACE VIEW, so what the app built on it (a view over a masked
  view) stays
- a table whose columns are the same: its rows written again
- anything else that changed or went: dropped first, with everything that needs it, then made again
- an inheritance tree whose definition is the same is not touched; one that changed is rebuilt
- steps (the base tables, checks, sweeps) run when their SQL changed, some (grants) every time

A new version of rowstile is a migration only when it makes something different: the lock holds a hash of
the steps every migration runs, beside everything else, and not the version it was written by.

The first migration, with no lock, is the whole compiled policy, which also applies over a database
that already has a policy. Each migration checks that the database is where the lock said (the lock's
hash is recorded in authz.policy_versions), and records the policy it leaves in force.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Iterable, Iterator
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from . import BUILD, __version__
from .compiler import NextTree
from .parse import meaning_lines
from .sqlutil import DROP_CHILD_TRIGGERS, STUB_COLUMNS
from .statements import drop_sql, made, references, split, unquoted

if TYPE_CHECKING:
    from . import Compiler

LOCK_HEADER = (
    "# rowstile {version}: what the migrations so far have made, for the next one to start from.\n"
    "# Generated by rowstile migrate; commit it with the migrations, and don't edit it.\n"
)
# statements a migration skips: the compiled policy's own settings, set once at the start of each migration
SETTINGS = re.compile(r"^\s*SET\s+LOCAL\s+check_function_bodies\b", re.IGNORECASE)


def digest(text: str, n: int = 12) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:n]


def code(sql: str) -> str:
    """The part of a statement that matters: without lines that are only comments."""
    return "\n".join(line for line in sql.split("\n") if not line.lstrip().startswith("--")).strip()


# --- the compiled policy, as objects -------------------------------------------------------------
@dataclass(eq=False)
class Obj:
    kind: str
    key: str
    stmts: list[tuple[str, str]]  # [(comments, sql)]: the statement that makes it, then what goes with it
    order: int
    tree: str | None = None  # the inheritance tree it belongs to

    @property
    def ident(self) -> str:
        return f"{self.kind} {self.key}"

    @property
    def name(self) -> str:
        return unquoted(self.key)

    @property
    def atomic(self) -> bool:
        return self.kind == "function" and re.search(r"\bBEGIN\s+ATOMIC\b", self.stmts[0][1], re.IGNORECASE) is not None

    @property
    def hash(self) -> str:
        return digest("\n;\n".join(code(s) for _, s in self.stmts))

    @property
    def shape(self) -> str | None:
        """What CREATE OR REPLACE can't change: a function's arguments (defaults too) and result; a table's columns."""
        first = code(self.stmts[0][1])
        if self.kind == "function":
            m = re.search(
                r"\b(LANGUAGE|AS\s+\$|BEGIN\s+ATOMIC|SECURITY|STABLE|IMMUTABLE|VOLATILE|SET\s)", first, re.IGNORECASE
            )
            return digest(first[: m.start()] if m else first, 8)
        if self.kind == "table":
            return digest(first, 8)
        return None

    def hard_refs(self) -> set[str]:
        """The names this object can't outlive: what a view, a policy, a trigger or an atomic function's
        body reads, and the types in a function's arguments and result. What a PL/pgSQL or SQL body
        calls is looked up when it runs, so it doesn't count."""
        first = self.stmts[0][1]
        if self.kind == "function" and not self.atomic:
            m = re.search(r"\bAS\s+\$", first, re.IGNORECASE)
            first = first[: m.start()] if m else first
        refs = references(first)
        refs.discard(self.name)
        return refs


@dataclass
class Step:
    name: str
    sql: str
    when: str  # 'changed': when its SQL changed; 'always'; 'created': also when functions or views were made
    order: int

    @property
    def hash(self) -> str:
        # a step runs again when what it does changed, not when the policy's lines moved
        return digest(re.sub(r"\bline \d+", "line", code(self.sql)))


@dataclass
class Tree:
    name: str
    sql: str
    hash: str
    objs: list[Obj]
    order: int
    next: NextTree | None = None  # how to build it beside the one in use (trees.next_tree), if it can be


@dataclass
class Compiled:
    items: list[Step | Obj | Tree]  # in the order the compiled policy makes them
    meaning: list[str]  # the policy's lines, normalized
    policy: str
    files: dict[str, str]

    def objects(self) -> Iterator[Obj]:
        for it in self.items:
            if isinstance(it, Obj):
                yield it
            elif isinstance(it, Tree):
                yield from it.objs


def read(compiler: Compiler, policy: str, files: dict[str, str]) -> Compiled:
    """The compiled policy as steps, objects and trees (compiler.parts, filled by compile())."""
    items: list[Step | Obj | Tree] = []
    made_so_far: list[Obj] = []
    order = 0
    cur: Obj | None = None
    for mode, name, sql in compiler.parts:
        order += 1
        if mode == "full":
            continue
        if mode in ("always", "changed", "created"):
            items.append(Step(name, sql, mode, order))
            cur = None
            continue
        objs: list[Obj] = []
        if mode == "tree":
            cur = None
        for comments, stmt in split(sql):
            order += 1
            m = made(stmt, comments)
            if m:
                cur = Obj(m[0], m[1], [(comments, stmt)], order, tree=name if mode == "tree" else None)
                objs.append(cur)
                made_so_far.append(cur)
                continue
            if SETTINGS.match(stmt):
                continue
            target = attached_to(stmt, made_so_far) or cur
            # (a part that makes something starts by making it: what makes nothing goes with the object before it)
            assert target is not None, f"a statement that makes nothing, with nothing before it: {stmt[:120]}"
            target.stmts.append((comments, stmt))
        if mode == "tree":
            cur = None
        if mode == "tree":
            h = compiler.tree_keep.get(name, (None,))[0] or digest(code(sql), 32)
            items.append(Tree(name, sql, h, objs, order, compiler.tree_next.get(name)))
        else:
            items += objs
    seen: dict[str, Obj] = {}
    for o in (o for it in items for o in ([it] if isinstance(it, Obj) else it.objs if isinstance(it, Tree) else [])):
        # (the compiler makes each object once: a view two tables' rules would name alike is refused, AZ109)
        assert o.ident not in seen, f"{o.ident} is made twice"
        seen[o.ident] = o
    return Compiled(items, meaning_lines(policy, files), policy, files)


def attached_to(stmt: str, objs: list[Obj]) -> Obj | None:
    """The object a statement that makes nothing belongs to, when it names it: INSERT INTO t, COMMENT ON."""
    m = re.match(r"\s*(?:INSERT\s+INTO|DELETE\s+FROM|COMMENT\s+ON\s+\w+)\s+(\S+)", stmt, re.IGNORECASE)
    if not m:
        return None
    name = unquoted(m.group(1))
    return next((o for o in reversed(objs) if o.name == name and o.kind in ("table", "view", "function")), None)


# --- the lock file ---------------------------------------------------------------------------------
class LockObject(TypedDict):
    """What the lock says of one object the migrations made."""

    kind: str
    key: str
    hash: str
    shape: str | None  # what CREATE OR REPLACE can't change (Obj.shape)
    tree: str | None
    atomic: bool


@dataclass
class Lock:
    version: str | None = None
    meaning: list[str] = field(default_factory=list)
    trees: dict[str, str] = field(default_factory=dict)  # name -> hash
    steps: dict[str, str] = field(default_factory=dict)  # name -> hash
    nexts: dict[str, str] = field(default_factory=dict)  # tree name -> hash: built beside, by the migration before
    always: str | None = None  # the steps every migration runs, hashed (none: a lock from before)
    objects: dict[str, LockObject] = field(default_factory=dict)  # 'kind key' -> what was made
    text: str = ""

    @property
    def empty(self) -> bool:
        return not self.objects and not self.trees

    @property
    def hash(self) -> str | None:
        return digest(self.text, 16) if self.text else None


class LockError(ValueError):
    """A line of a lock file that rowstile migrate doesn't write: most often a conflict marker a merge left."""

    def __init__(self, n: int, line: str) -> None:
        super().__init__(f"line {n} of the lock file isn't one rowstile migrate writes ({line.strip()[:40]})")


def always_hash(c: Compiled) -> str:
    """The steps every migration runs, as one hash: a new version of rowstile that changes one of them is a
    migration, even when nothing else changed."""
    return digest("\n".join(it.hash for it in c.items if isinstance(it, Step) and it.when == "always"))


def lock_of(c: Compiled) -> str:
    lines = [f"> {line}" for line in c.meaning] + [f"always | {always_hash(c)}"]
    for it in c.items:
        if isinstance(it, Step) and it.when != "always":
            lines.append(f"step {it.name} | {it.hash}")
        elif isinstance(it, Tree):
            lines.append(f"tree {it.name} | {it.hash}")
    for o in c.objects():
        attrs = (
            [o.hash]
            + ([f"shape={o.shape}"] if o.shape else [])
            + (["atomic"] if o.atomic else [])
            + ([f"tree={o.tree}"] if o.tree else [])
        )
        lines.append(f"{o.ident} | {' '.join(attrs)}")
    meaning = [x for x in lines if x.startswith("> ")]
    rest = sorted(x for x in lines if not x.startswith("> "))
    return LOCK_HEADER.format(version=__version__) + "\n".join(meaning + [""] + rest) + "\n"


def parse_lock(text: str | None) -> Lock:
    """The lock file's text read; LockError for a line that is none of the policy's nor says what was made (a
    merge's conflict marker, say)."""
    lock = Lock(text=text or "")
    for n, line in enumerate((text or "").split("\n"), 1):
        if line.startswith(("# rowstile ", "# rowfence ", "# authzc ")):  # rowstile's names before, too
            lock.version = line.split()[2].rstrip(":")
        if not line or line.startswith("#"):
            continue
        if line.startswith("> "):
            lock.meaning.append(line[2:])
            continue
        head, _, attrs = line.partition(" | ")
        kind, _, key = head.partition(" ")
        words = attrs.split()
        if not words:  # each line of what was made gives its hash after a bar
            raise LockError(n, line)
        if kind == "tree":
            lock.trees[key] = words[0]
        elif kind == "step":
            lock.steps[key] = words[0]
        elif kind == "next":
            lock.nexts[key] = words[0]
        elif kind == "always":
            lock.always = words[0]
        else:
            info: LockObject = {
                "kind": kind,
                "key": key,
                "hash": words[0],
                "shape": None,
                "tree": None,
                "atomic": False,
            }
            for w in words[1:]:
                if w == "atomic":
                    info["atomic"] = True
                elif w.startswith("shape="):
                    info["shape"] = w[len("shape=") :]
                elif w.startswith("tree="):
                    info["tree"] = w[len("tree=") :]
            lock.objects[head] = info
    return lock


# --- a migration -----------------------------------------------------------------------------------
@dataclass
class Migration:
    sql: str  # empty: nothing to do
    lock: str  # the lock file after it
    summary: list[str]  # what changed, in plain words (the migration's first comment lines)
    rebuilt: list[str]  # inheritance trees it rebuilds
    locks: list[str]  # app tables it changes policies or triggers on (they are locked while it runs)

    @property
    def empty(self) -> bool:
        return not self.sql


# A migration is one transaction: it uses temporary tables and settings that end with it, and its statements only
# make sense together. Run a statement at a time (psql -f without -1: each one commits), a tree change would stop
# half way with the old tree dropped. So it marks its transaction, and where the mark is gone by the next statement
# it makes the session read-only first (psql goes on after an error unless told to stop) and then says so.
ONE_TRANSACTION = """-- a migration is one transaction: outside one, nothing below changes anything
SELECT pg_catalog.set_config('authz_ctx.migration', {mark}, true);
DO $authz_tx$
BEGIN
  IF pg_catalog.current_setting('authz_ctx.migration', true) IS DISTINCT FROM {mark} THEN
    PERFORM pg_catalog.set_config('default_transaction_read_only', 'on', false);
  END IF;
END $authz_tx$;
DO $authz_tx$
BEGIN
  IF pg_catalog.current_setting('authz_ctx.migration', true) IS DISTINCT FROM {mark} THEN
    RAISE EXCEPTION 'rowstile: this migration must run in one transaction, and its statements are being committed one by one [AZ615]'
      USING HINT = 'nothing was changed, and this session is read-only from here on; run the file with your migration tool, or with psql -1 -f';
  END IF;
END $authz_tx$;"""

DROP_ORDER = ["policy", "trigger", "atomic", "view", "function", "index", "table", "type"]
# where the policy's lines are, for messages: a change to it alone (lines that moved) needs no migration
SOFT = "table authz_gen.policy_lines"
LOCKS = "authz_int.locks"  # the type-wide lock rows every tree write takes (trees.lock_sql)


def migration(compiled_sql: str, c: Compiled, old: Lock, name: str = "policy", lines: bool = False) -> Migration:
    """The migration from the lock `old` to the compiled policy `c`. compiled_sql is the whole policy
    (compile(transaction=False)), used when there is no lock yet. With lines, lines that only moved are
    a migration too (rowstile push: a development database's messages name the lines as they are)."""
    new_lock = lock_of(c)
    summary = describe(old, c)
    new_hash = digest(new_lock, 16)
    if not old.empty and old.text == new_lock:
        return Migration("", new_lock, [], [], [])
    if old.empty:
        body = compiled_sql
        rebuilt = [it.name for it in c.items if isinstance(it, Tree)]
        return Migration(
            render(name, summary, None, body, c, new_hash), new_lock, summary, rebuilt, sorted(app_tables(c.objects()))
        )

    objs = {o.ident: o for o in c.objects()}
    trees = [it for it in c.items if isinstance(it, Tree)]
    rebuild = {t.name for t in trees if old.trees.get(t.name) != t.hash}
    drop: set[str] = set()
    create: set[str] = set()
    replace: set[str] = set()
    restub: set[str] = set()  # views emptied in place, then defined again: never dropped while they stay
    # in place means the same columns. A masked view's are its table's; a generated view's one column is its
    # type's key, so when a type line changed (a key of another type, maybe) those are dropped and made again
    type_lines = [[x for x in lines if re.match(r"type\s+\w+\s*=", x)] for lines in (old.meaning, c.meaning)]
    same_keys = type_lines[0] == type_lines[1]

    def in_place(o: Obj) -> bool:
        return (
            o.kind == "view"
            and not o.tree
            and o.ident in old.objects
            and (same_keys or not o.name.startswith(("authz_int.", "authz_gen.")))
        )

    refill: set[str] = set()
    for o in c.objects():
        if o.tree:
            continue
        prev = old.objects.get(o.ident)
        if prev is None:
            create.add(o.ident)
        elif prev["hash"] != o.hash:
            # an atomic body's old version may need what goes: those are made again, not replaced
            if o.kind == "function" and prev["shape"] == o.shape and not o.atomic and not prev["atomic"]:
                replace.add(o.ident)
            elif in_place(o):
                restub.add(o.ident)
            elif o.kind == "table" and prev["shape"] == o.shape:
                refill.add(o.ident)
            elif o.kind == "rls":
                create.add(o.ident)
            else:
                drop.add(o.ident)
                create.add(o.ident)
    removed = {k for k, info in old.objects.items() if k not in objs or (info["tree"] in rebuild)}
    removed |= {k for k, info in old.objects.items() if info["tree"] and info["tree"] not in {t.name for t in trees}}
    steps = {
        it.name for it in c.items if isinstance(it, Step) and it.when == "changed" and old.steps.get(it.name) != it.hash
    }
    changed = drop or create or replace or restub or removed or rebuild or steps or refill - {SOFT}
    # a lock from before the steps were hashed can only say which version wrote it
    same_steps = old.always == always_hash(c) if old.always else old.version == __version__
    if not lines and not changed and same_steps:
        # only lines moved, or only the version of rowstile changed: that alone needs no migration; the next one
        # writes the new lines (and version) too
        return Migration("", old.text, [], [], [])
    # what can't outlive a dropped object is dropped and made again with it
    gone = {unquoted(old.objects[k]["key"]) for k in removed} | {objs[k].name for k in drop}
    while True:
        more: set[Obj] = set()
        for o in c.objects():
            if o.ident in drop or o.ident in restub or (o.tree and o.tree in rebuild):
                continue
            if o.hard_refs() & gone:
                more.add(o)
        if not more:
            break
        for o in more:
            # (a tree's objects read the app's tables and the tree's own objects alone, as trees.py writes them)
            assert not o.tree, f"{o.ident}, of the tree {o.tree}, reads what goes"
            if in_place(o):
                restub.add(o.ident)  # it stays, reading nothing, while what it read goes: nothing on it has to go
            else:
                drop.add(o.ident)
                create.add(o.ident)
                replace.discard(o.ident)
                refill.discard(o.ident)
                gone.add(o.name)

    # drops: what is removed or made again, ordered so nothing is dropped before what needs it
    victims: dict[str, tuple[str, str]] = {}
    for k in removed:
        info = old.objects[k]
        victims[k] = ("atomic" if info["atomic"] else info["kind"], info["key"])
    for k in drop:
        o = objs[k]
        victims[k] = ("atomic" if o.atomic else o.kind, o.key)
    drops: list[str] = []
    lost_rules: list[str] = []
    for kind in DROP_ORDER:
        keys = sorted(key for (kd, key) in victims.values() if kd == kind)
        if not keys:
            continue
        if kind in ("atomic", "view", "function", "table", "type"):
            word = {"atomic": "FUNCTION", "view": "VIEW", "function": "FUNCTION", "table": "TABLE", "type": "TYPE"}[
                kind
            ]
            drops.append(f"DROP {word} IF EXISTS\n  " + ",\n  ".join(keys) + ";")
        else:
            drops += [sql for key in keys if (sql := drop_sql(kind, key))]
    for k in removed:
        if old.objects[k]["kind"] == "rls" and k not in objs:
            lost_rules.append(old.objects[k]["key"])
    # dynamic triggers a rebuilt tree made on the tables its conditions read
    dyn = [f"authz_{t}_dep" for t in sorted(rebuild)]

    # what is made, in the compiled policy's order; steps that grant on what was made run if anything was
    made_any = bool(create or rebuild)
    body: list[str] = []
    for it in c.items:
        if isinstance(it, Step):
            if it.when == "always" or old.steps.get(it.name) != it.hash or (it.when == "created" and made_any):
                body.append(it.sql)
        elif isinstance(it, Tree):
            if it.name in rebuild:
                body.append(it.sql)
        elif it.ident in create or it.ident in replace or it.ident in restub:
            stmts = list(it.stmts)
            if it.ident in replace:
                stmts[0] = (
                    stmts[0][0],
                    re.sub(
                        r"^(\s*)CREATE\s+FUNCTION",
                        r"\1CREATE OR REPLACE FUNCTION",
                        stmts[0][1],
                        count=1,
                        flags=re.IGNORECASE,
                    ),
                )
            if it.ident in restub:  # (a masked view's own statement replaces it in place already)
                stmts[0] = (
                    stmts[0][0],
                    re.sub(
                        r"^(\s*)CREATE\s+VIEW", r"\1CREATE OR REPLACE VIEW", stmts[0][1], count=1, flags=re.IGNORECASE
                    ),
                )
            body.append(statements_sql(stmts))
        elif it.ident in refill:
            rows = [(cm, s) for cm, s in it.stmts[1:] if re.match(r"\s*(INSERT|DO)\b", s, re.IGNORECASE)]
            # The lock rows stay: a tree write that waits on one while the migration runs must find the same row
            # after it, or it goes on without the lock. Their inserts do nothing where the row is there, and a
            # row for a type with no tree any more is harmless.
            delete = "" if it.key == LOCKS else f"DELETE FROM {it.key};\n"
            body.append(f"-- {it.key}: its rows again\n{delete}" + statements_sql(rows))

    parts: list[str] = []
    if dyn:
        parts.append(
            "-- the triggers rebuilt trees made on tables their conditions read\nDO $authz_dyn$\nDECLARE r record;\nBEGIN\n"
            "  FOR r IN SELECT t.tgname, t.tgrelid::regclass AS tbl FROM pg_catalog.pg_trigger t\n"
            f"           WHERE t.tgname = ANY (ARRAY[{', '.join(sql_lit(x) for x in dyn)}]) LOOP\n"
            "    EXECUTE format('DROP TRIGGER %I ON %s', r.tgname, r.tbl);\n  END LOOP;\nEND $authz_dyn$;"
        )
    if restub:
        names = ", ".join(sql_lit(objs[k].key) for k in sorted(restub))
        parts.append(
            "-- views that change stay where they are, emptied (the same columns, reading nothing) while what they\n"
            "-- read is dropped and made again; they are defined again below. What the app built on one stays\n"
            "DO $authz_stub$\nDECLARE v text; cols text;\nBEGIN\n"
            f"  FOREACH v IN ARRAY ARRAY[{names}] LOOP\n"
            "    CONTINUE WHEN pg_catalog.to_regclass(v) IS NULL;\n"
            "    SELECT " + STUB_COLUMNS.replace("VIEW", "pg_catalog.to_regclass(v)") + " INTO cols;\n"
            "    EXECUTE format('CREATE OR REPLACE VIEW %s AS SELECT %s WHERE false', v, cols);\n"
            "  END LOOP;\nEND $authz_stub$;"
        )
    if drops:
        # (they call functions that may be among the drops; the step every migration runs makes them again)
        parts.append(DROP_CHILD_TRIGGERS)
        parts.append("-- what goes, or is made again\n" + "\n".join(drops))
    swapped = [t for t in trees if t.name in rebuild and t.next and old.nexts.get(t.name) == t.hash]
    if rebuild:
        parts.append(
            "-- rebuilt inheritance trees start empty\n"
            "CREATE TEMP TABLE IF NOT EXISTS authz_kept (name text PRIMARY KEY) ON COMMIT DROP;"
        )
    if swapped:
        parts.insert(
            0,
            "-- trees built beside the ones in use (by the migration before) take their place\n"
            "CREATE SCHEMA IF NOT EXISTS authz_keep;\n" + "\n".join(swap_sql(t) for t in swapped),
        )
    parts += body
    for t in swapped:
        assert t.next is not None  # (a tree is swapped in only where the migration before built it beside)
        parts.insert(parts.index(t.sql) + 1, t.next["catch_up"])
    if swapped:
        parts.append(
            "DROP SCHEMA IF EXISTS authz_keep CASCADE;\n"
            "DO $authz_built$ BEGIN\n"
            "  IF NOT EXISTS (SELECT 1 FROM authz_int.next_trees) THEN DROP TABLE authz_int.next_trees; END IF;\n"
            "END $authz_built$;"
        )
    for tbl in sorted(lost_rules):
        parts.append(
            f"DO $authz_lost$ BEGIN\n  RAISE WARNING '% has no rules any more, and row-level security is still on, "
            f"so the app role sees none of its rows. If that is not what you want: ALTER TABLE % DISABLE ROW "
            f"LEVEL SECURITY', {sql_lit(tbl)}, {sql_lit(tbl)};\nEND $authz_lost$;"
        )
    touched = [objs[k] for k in create | replace | restub | refill if k in objs] + [
        o for t in trees if t.name in rebuild for o in t.objs
    ]
    body_sql = "\n\n".join(parts)
    return Migration(
        render(name, summary, old.hash, body_sql, c, new_hash),
        new_lock,
        summary,
        sorted(rebuild),
        sorted(
            app_tables(touched) | {key.split(" ON ")[1] for kd, key in victims.values() if kd in ("policy", "trigger")}
        ),
    )


def swap_sql(t: Tree) -> str:
    """The tree built beside, moved where the tree's SQL keeps it (trees.swap_in_kept), its indexes renamed."""
    n = t.next
    assert n is not None, f"{t.name} can't be built beside"
    return (
        f"ALTER TABLE {n['next']} SET SCHEMA authz_keep;\n"
        f"ALTER TABLE authz_keep.{n['next_name']} RENAME TO {n['table']};\n"
        f"DO $authz_swap$\nDECLARE r record;\nBEGIN\n"
        f"  FOR r IN SELECT c.relname FROM pg_catalog.pg_index i JOIN pg_catalog.pg_class c ON c.oid = i.indexrelid\n"
        f"           WHERE i.indrelid = to_regclass({sql_lit('authz_keep.' + n['table'])}) LOOP\n"
        f"    EXECUTE format('ALTER INDEX authz_keep.%I RENAME TO %I', r.relname,\n"
        f"                   replace(r.relname, {sql_lit(t.name + '__next')}, {sql_lit(t.name)}));\n"
        f"  END LOOP;\nEND $authz_swap$;"
    )


def watched(old: Lock, table: str) -> bool:
    """The old policy's relationship triggers on a link table feed its inserts, updates and deletes."""
    name = unquoted(table)
    ops = {
        m.group(1)
        for info in old.objects.values()
        if info["kind"] == "trigger"
        for m in [re.match(r'"?authz_rel_audit_\d+_(ins|upd|del)"? ON (.+)$', info["key"])]
        if m and unquoted(m.group(2)) == name
    }
    return ops >= {"ins", "upd", "del"}


def migrations(
    compiled_sql: str, c: Compiled, old: Lock, name: str = "policy", two_phase: bool = True
) -> list[Migration]:
    """The migrations from the lock `old` to the policy `c`: one; or two when inheritance trees are rebuilt
    and can be built beside the ones in use first. The first builds them while the app runs,
    reading its tables only; the second swaps them in, in a short transaction, and does again what changed
    in between. A tree can be built beside when it is of one type, its conditions read only its own rows,
    it takes no links from shares, and the policy in force already feeds the changes to its link tables."""
    if old.empty or not two_phase:
        return [migration(compiled_sql, c, old, name)]
    todo = [
        t
        for t in c.items
        if isinstance(t, Tree)
        and t.next is not None
        and old.trees.get(t.name) != t.hash
        and old.nexts.get(t.name) != t.hash
        and all(watched(old, lt) for lt in t.next["link_tables"])
    ]
    if not todo:
        return [migration(compiled_sql, c, old, name)]
    first = build_migration(c, old, todo, name)
    return [first, migration(compiled_sql, c, parse_lock(first.lock), name)]


def build_migration(c: Compiled, old: Lock, trees: list[Tree], name: str) -> Migration:
    lines = old.text.rstrip("\n").split("\n")
    lines = [x for x in lines if not any(x.startswith(f"next {t.name} ") for t in trees)]
    body = [
        "-- what the trees are built from: this snapshot, then what changed since (the next migration)\n"
        "CREATE TABLE IF NOT EXISTS authz_int.next_trees (name text PRIMARY KEY, hash text NOT NULL, "
        "snap pg_snapshot NOT NULL, feed bigint NOT NULL);"
    ]
    for t in trees:
        n = t.next
        assert n is not None, f"{t.name} can't be built beside"
        drops = "\n".join(
            f"DROP {'TABLE' if kind == 'table' else 'FUNCTION'} IF EXISTS {key};" for kind, key in n["objects"]
        )
        body.append(
            f"-- {t.name}: built beside the one in use, reading the app's tables only (the app keeps working)\n"
            f"DELETE FROM authz_int.next_trees WHERE name = {sql_lit(t.name)};\n{drops}\n"
            f"INSERT INTO authz_int.next_trees VALUES ({sql_lit(t.name)}, {sql_lit(t.hash)}, "
            f"pg_catalog.pg_current_snapshot(), (SELECT coalesce(max(pos), 0) FROM authz.changes));\n" + n["build"]
        )
        lines.append(f"next {t.name} | {t.hash}")
        for kind, key in n["objects"]:
            lines.append(f"{kind} {key} | {digest(n['build'] + key)}")
    head = [x for x in lines if x.startswith("#")]
    meaning = [x for x in lines if x.startswith("> ")]
    rest = sorted(x for x in lines if x and not x.startswith(("#", "> ")))
    lock = "\n".join(head + meaning + [""] + rest) + "\n"
    new_hash = digest(lock, 16)
    summary = [
        f"builds {', '.join(t.name for t in trees)} beside the ones in use; the next migration swaps "
        f"{'them' if len(trees) > 1 else 'it'} in"
    ]
    sql = render(f"{name} (1 of 2)", summary, old.hash, "\n\n".join(body), c, new_hash, record=False)
    return Migration(sql, lock, summary, [t.name for t in trees], [])


def statements_sql(stmts: Iterable[tuple[str, str]]) -> str:
    return "\n".join((f"{cm}\n" if cm else "") + s + ";" for cm, s in stmts)


def sql_lit(s: object) -> str:
    return "'" + str(s).replace("'", "''") + "'"


def app_tables(objs: Iterable[Obj]) -> set[str]:
    out: set[str] = set()
    for o in objs:
        if o.kind in ("policy", "trigger"):
            tbl = o.key.split(" ON ")[1]
            if not tbl.split(".")[0].strip('"').startswith("authz"):
                out.add(tbl)
        elif o.kind == "rls":
            out.add(o.key)
    return out


def dollar(text: str, tag: str = "authz_policy") -> str:
    while f"${tag}$" in text:
        tag += "_"
    return f"${tag}${text}${tag}$"


def render(
    name: str, summary: list[str], old_hash: str | None, body: str, c: Compiled, new_hash: str, record: bool = True
) -> str:
    head = [
        f"-- rowstile {__version__}: {name}. Generated by rowstile migrate from the policy; don't edit it,",
        "-- change the policy and write the next migration.",
    ]
    head += [f"-- {line}" for line in summary] if summary else []
    out = ["\n".join(head), ONE_TRANSACTION.format(mark=sql_lit(new_hash))]
    out.append(
        "SELECT pg_catalog.set_config('lock_timeout', '10s', true) WHERE pg_catalog.current_setting('lock_timeout') IN ('0', '0ms');\n"
        "SELECT pg_catalog.set_config('check_function_bodies', 'off', true);"
    )
    if old_hash:
        # a database that holds the lock this migration makes (it ran here already, or dev or push took a
        # development database there, where most people meet the guard) is told so, with what to tell the tool
        there = (
            f"""IF v_lock = {sql_lit(new_hash)} THEN
    RAISE EXCEPTION 'rowstile: this database already holds what this migration brings (it ran here before, or rowstile dev or push took the database there): don''t run it, tell your migration tool it is applied [AZ607]'
      USING HINT = 'Prisma: prisma migrate resolve --applied <the migration''s folder>. Alembic: alembic stamp head. '
                   'Others, and why: rowstile help AZ607';
  ELSIF"""
            if new_hash != old_hash
            else "IF"
        )
        out.append(f"""-- this migration starts from the policy the previous one left
DO $authz_guard$
DECLARE v_lock text;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_catalog.pg_attribute
             WHERE attrelid = to_regclass('authz.policy_versions') AND attname = 'lock' AND NOT attisdropped) THEN
    EXECUTE 'SELECT lock FROM authz.policy_versions ORDER BY id DESC LIMIT 1' INTO v_lock;
  END IF;
  {there} v_lock IS DISTINCT FROM {sql_lit(old_hash)} THEN
    RAISE EXCEPTION 'rowstile: this migration changes the policy the migration before it left (%), but the database has % [AZ607]',
      {sql_lit(old_hash)}, coalesce(v_lock, 'none')
      USING HINT = 'apply the migrations in order; a database changed with rowstile push or apply since needs the '
                   'migrations from the start (or rowstile apply of the policy the previous migration left) '
                   '(rowstile help AZ607)';
  END IF;
END $authz_guard$;""")
    out.append(body)
    if not record:
        out.append(
            "-- the policy in force is the same; the next migration starts from here\n"
            f"UPDATE authz.policy_versions SET lock = {sql_lit(new_hash)} WHERE id = (SELECT max(id) FROM authz.policy_versions);"
        )
        return "\n\n".join(x for x in out if x.strip()) + "\n"
    files = json.dumps(c.files or {}, sort_keys=True)
    out.append(
        "-- the policy now in force\n"
        "INSERT INTO authz.policy_versions (action, policy, files, version, lock)\n"
        f"VALUES ('apply', {dollar(c.policy)},\n  {dollar(files, 'authz_files')}::jsonb, {sql_lit(BUILD)}, {sql_lit(new_hash)});"
    )
    return "\n\n".join(x for x in out if x.strip()) + "\n"


def describe(old: Lock, c: Compiled) -> list[str]:
    """What changed in the policy's lines, for the first comments of the migration."""
    if old.empty:
        return [f"the whole policy ({len(c.meaning)} lines)"]
    before, after = set(old.meaning), set(c.meaning)
    out = [f"- {x}" for x in old.meaning if x not in after] + [f"+ {x}" for x in c.meaning if x not in before]
    if not out and old.version != __version__:
        out = [f"rowstile {old.version} -> {__version__}: what the new version makes differently"]
    elif not out:
        out = ["the same policy; what rowstile makes of it changed"]
    return out
