-- rowfence 0.1.0-dev: partitions_rls. Generated by rowfence migrate from the policy; don't edit it,
-- change the policy and write the next migration.
-- the same policy; what rowfence makes of it changed

SELECT pg_catalog.set_config('lock_timeout', '10s', true) WHERE pg_catalog.current_setting('lock_timeout') IN ('0', '0ms');
SELECT pg_catalog.set_config('check_function_bodies', 'off', true);

-- this migration starts from the policy the previous one left
DO $authz_guard$
DECLARE v_lock text;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_catalog.pg_attribute
             WHERE attrelid = to_regclass('authz.policy_versions') AND attname = 'lock' AND NOT attisdropped) THEN
    EXECUTE 'SELECT lock FROM authz.policy_versions ORDER BY id DESC LIMIT 1' INTO v_lock;
  END IF;
  IF v_lock IS DISTINCT FROM 'a0afcf70fa8d4067' THEN
    RAISE EXCEPTION 'rowfence: this migration changes the policy the migration before it left (%), but the database has % [AZ607]',
      'a0afcf70fa8d4067', coalesce(v_lock, 'none')
      USING HINT = 'apply the migrations in order; a database changed with rowfence push or apply since needs the '
                   'migrations from the start (or rowfence apply of the policy the previous migration left)';
  END IF;
END $authz_guard$;

-- Functions below resolve names with the search_path in effect now, temporary schema last
DO $sp$ BEGIN PERFORM pg_catalog.set_config('search_path', pg_catalog.concat_ws(', ',
  nullif(pg_catalog.current_setting('search_path'), ''), 'pg_temp'), true); END $sp$;

ALTER TABLE "app"."projects" ENABLE ROW LEVEL SECURITY;
-- its partitions and the tables that inherit from it: row-level security on, with no policies of their own,
-- so they are read and written through it only (read directly, they would skip its rules and triggers)
DO $rls$
DECLARE c regclass;
BEGIN
  FOR c IN WITH RECURSIVE d(oid) AS (
             SELECT i.inhrelid FROM pg_catalog.pg_inherits i WHERE i.inhparent = '"app"."projects"'::regclass
             UNION SELECT i.inhrelid FROM pg_catalog.pg_inherits i JOIN d ON i.inhparent = d.oid)
           SELECT d.oid::regclass FROM d JOIN pg_catalog.pg_class k ON k.oid = d.oid WHERE NOT k.relrowsecurity LOOP
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', c);
  END LOOP;
END $rls$;

ALTER TABLE "app"."notes" ENABLE ROW LEVEL SECURITY;
-- its partitions and the tables that inherit from it: row-level security on, with no policies of their own,
-- so they are read and written through it only (read directly, they would skip its rules and triggers)
DO $rls$
DECLARE c regclass;
BEGIN
  FOR c IN WITH RECURSIVE d(oid) AS (
             SELECT i.inhrelid FROM pg_catalog.pg_inherits i WHERE i.inhparent = '"app"."notes"'::regclass
             UNION SELECT i.inhrelid FROM pg_catalog.pg_inherits i JOIN d ON i.inhparent = d.oid)
           SELECT d.oid::regclass FROM d JOIN pg_catalog.pg_class k ON k.oid = d.oid WHERE NOT k.relrowsecurity LOOP
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', c);
  END LOOP;
END $rls$;

ALTER TABLE "app"."inbox" ENABLE ROW LEVEL SECURITY;
-- its partitions and the tables that inherit from it: row-level security on, with no policies of their own,
-- so they are read and written through it only (read directly, they would skip its rules and triggers)
DO $rls$
DECLARE c regclass;
BEGIN
  FOR c IN WITH RECURSIVE d(oid) AS (
             SELECT i.inhrelid FROM pg_catalog.pg_inherits i WHERE i.inhparent = '"app"."inbox"'::regclass
             UNION SELECT i.inhrelid FROM pg_catalog.pg_inherits i JOIN d ON i.inhparent = d.oid)
           SELECT d.oid::regclass FROM d JOIN pg_catalog.pg_class k ON k.oid = d.oid WHERE NOT k.relrowsecurity LOOP
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', c);
  END LOOP;
END $rls$;

-- Leaks: SELECT * FROM authz.lint()  (administrators; run after schema changes)
CREATE OR REPLACE FUNCTION authz.lint() RETURNS TABLE (severity text, object text, problem text)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $f$
DECLARE r record; v_role oid := to_regrole('conf_app');
BEGIN
  IF v_role IS NULL THEN
    severity := 'error'; object := 'conf_app'; problem := 'the app role does not exist'; RETURN NEXT; RETURN;
  END IF;
  -- the app role itself
  FOR r IN SELECT rolsuper, rolbypassrls FROM pg_roles WHERE oid = v_role AND (rolsuper OR rolbypassrls) LOOP
    severity := 'error'; object := 'conf_app';
    problem := 'is a superuser or has BYPASSRLS: row-level security does not apply to it at all'; RETURN NEXT;
  END LOOP;
  FOR r IN SELECT p.oid::regrole AS parent FROM pg_roles p
           WHERE p.oid <> v_role AND (p.rolsuper OR p.rolbypassrls) AND pg_has_role(v_role, p.oid, 'MEMBER') LOOP
    severity := 'error'; object := 'conf_app';
    problem := format('is a member of %s, which bypasses row-level security', r.parent); RETURN NEXT;
  END LOOP;
  -- governed tables
  FOR r IN SELECT c.oid::regclass AS tbl, c.relrowsecurity, c.relforcerowsecurity, c.relowner
           FROM pg_class c WHERE c.oid = ANY (SELECT to_regclass(x) FROM unnest(ARRAY['"app"."inbox"', '"app"."notes"', '"app"."projects"', '"app"."services"', '"app"."users"']::text[]) x) LOOP
    IF r.relowner = v_role OR pg_has_role(v_role, r.relowner, 'MEMBER') THEN
      IF NOT r.relforcerowsecurity THEN
        severity := 'error'; object := r.tbl::text;
        problem := format('is owned by %s (or a role it belongs to): owners skip row-level security unless you ALTER TABLE %s FORCE ROW LEVEL SECURITY', 'conf_app', r.tbl);
        RETURN NEXT;
      END IF;
    END IF;
    IF NOT r.relrowsecurity AND has_table_privilege(v_role, r.tbl, 'SELECT') THEN
      severity := 'info'; object := r.tbl::text;
      problem := format('%s may read every row (the policy has no rules for this table): fine for a directory, otherwise add rules', 'conf_app');
      RETURN NEXT;
    END IF;
    IF has_table_privilege(v_role, r.tbl, 'TRUNCATE') THEN
      severity := 'error'; object := r.tbl::text;
      problem := format('%s may TRUNCATE it, which skips row-level security: REVOKE TRUNCATE ON %s FROM %s', 'conf_app', r.tbl, 'conf_app');
      RETURN NEXT;
    END IF;
  END LOOP;
  -- partitions and inheritance children: used directly, they skip the rules and the triggers of the table above
  -- (apply turns row-level security on for the ones there are then; later ones are found here)
  FOR r IN WITH RECURSIVE d(oid, top, governed) AS (
             SELECT i.inhrelid, i.inhparent, x.governed FROM pg_inherits i
             JOIN (SELECT to_regclass(t) AS tbl, true AS governed FROM unnest(ARRAY['"app"."inbox"', '"app"."notes"', '"app"."projects"']::text[]) t
                   UNION ALL SELECT to_regclass(t), false FROM unnest(ARRAY['"app"."members"', '"app"."project_services"']::text[]) t) x
               ON i.inhparent = x.tbl
             UNION SELECT i.inhrelid, d.top, d.governed FROM pg_inherits i JOIN d ON i.inhparent = d.oid)
           SELECT d.oid::regclass AS part, d.top::regclass AS tbl, d.governed, k.relrowsecurity
           FROM d JOIN pg_class k ON k.oid = d.oid LOOP
    IF has_table_privilege(v_role, r.part, 'TRUNCATE') THEN
      severity := 'error'; object := r.part::text;
      problem := format('is a partition of %s (or inherits from it), and %s may TRUNCATE it, which skips row-level security and %s''s triggers: REVOKE TRUNCATE ON %s FROM %s', r.tbl, 'conf_app', r.tbl, r.part, 'conf_app');
      RETURN NEXT;
    END IF;
    IF NOT r.relrowsecurity AND (has_table_privilege(v_role, r.part, 'INSERT') OR has_table_privilege(v_role, r.part, 'UPDATE')
                                 OR has_table_privilege(v_role, r.part, 'DELETE')
                                 OR (r.governed AND has_table_privilege(v_role, r.part, 'SELECT'))) THEN
      severity := 'error'; object := r.part::text;
      problem := format('is a partition of %s (or inherits from it), and %s may use it directly, without %s''s rules or the triggers that keep inheritance and the audit current: apply the policy again (it turns row-level security on for it), or ALTER TABLE %s ENABLE ROW LEVEL SECURITY', r.tbl, 'conf_app', r.tbl, r.part);
      RETURN NEXT;
    END IF;
  END LOOP;
  -- unique constraints on governed tables tell people that rows they cannot see exist
  FOR r IN SELECT i.indexrelid::regclass AS idx, i.indrelid::regclass AS tbl
           FROM pg_index i WHERE i.indisunique AND NOT i.indisprimary
             AND i.indrelid = ANY (SELECT to_regclass(x) FROM unnest(ARRAY['"app"."inbox"', '"app"."notes"', '"app"."projects"']::text[]) x)
             AND has_table_privilege(v_role, i.indrelid, 'INSERT') LOOP
    severity := 'info'; object := r.idx::text;
    problem := format('a unique index on %s: inserting a duplicate fails even when the existing row is hidden, which tells the user it exists', r.tbl);
    RETURN NEXT;
  END LOOP;
  -- masked columns must only be readable through their view
  FOR r IN SELECT m.tbl, m.col, m.view FROM authz_int.masked_columns m
           WHERE CASE WHEN EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = to_regclass(m.tbl) AND a.attname = m.col
                                   AND a.attnum > 0 AND NOT a.attisdropped)
                      THEN has_column_privilege(v_role, m.tbl, m.col, 'SELECT') ELSE false END LOOP
    severity := 'error'; object := to_regclass(r.tbl)::text || '.' || r.col;
    problem := format('the policy masks it, but %s may read it from the table (a GRANT to the role, a role it belongs to, or PUBLIC): read it through %s and revoke that', 'conf_app', r.view);
    RETURN NEXT;
  END LOOP;
  -- tables holding relationships (memberships, links) the app role may change directly
  FOR r IN SELECT to_regclass(x) AS tbl FROM unnest(ARRAY['"app"."members"', '"app"."project_services"']::text[]) x LOOP
    CONTINUE WHEN r.tbl IS NULL;
    IF has_table_privilege(v_role, r.tbl, 'TRUNCATE') THEN
      severity := 'error'; object := r.tbl::text;
      problem := format('%s may TRUNCATE it, which empties memberships without row-level security: REVOKE TRUNCATE ON %s FROM %s', 'conf_app', r.tbl, 'conf_app');
      RETURN NEXT;
    END IF;
    IF (has_table_privilege(v_role, r.tbl, 'INSERT') OR has_table_privilege(v_role, r.tbl, 'UPDATE')
        OR has_table_privilege(v_role, r.tbl, 'DELETE'))
       AND NOT (SELECT relrowsecurity FROM pg_class WHERE oid = r.tbl) THEN
      severity := 'error'; object := r.tbl::text;
      problem := format('%s may change it, and it decides who is in what: anyone could add themselves. Revoke the write privileges, or give it rules', 'conf_app');
      RETURN NEXT;
    END IF;
  END LOOP;
  -- columns that grant a relation, changed by anyone who may update the row
  FOR r IN SELECT * FROM (VALUES ('"app"."notes"', 'project_id', 'note.project', 'relation note.project project_id'), ('"app"."notes"', 'author_id', 'note.author', 'relation note.author author_id')) v(tbl, col, what, loc)
           WHERE tbl IS NOT NULL LOOP
    IF EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = to_regclass(r.tbl) AND a.attname = r.col
               AND a.attnum > 0 AND NOT a.attisdropped)
       AND has_column_privilege(v_role, r.tbl, r.col, 'UPDATE') THEN
      severity := 'warning'; object := to_regclass(r.tbl)::text || '.' || r.col;
      problem := format('grants %s (%s), and anyone who may update the row may change it: add a rule such as "update %s : share"', r.what, coalesce((SELECT l.loc FROM authz_gen.policy_lines l WHERE l.what = r.loc), '?'), r.col);
      RETURN NEXT;
    END IF;
  END LOOP;
  -- JIT for the app role: checks are many small subplans, which JIT may spend longer compiling than running
  IF coalesce((SELECT split_part(c, '=', 2) FROM pg_db_role_setting s, unnest(s.setconfig) c
               WHERE s.setrole = v_role AND c LIKE 'jit=%'
                 AND s.setdatabase IN (0, (SELECT d.oid FROM pg_database d WHERE d.datname = current_database()))
               ORDER BY s.setdatabase DESC LIMIT 1), current_setting('jit')) IN ('on', 'true', '1') THEN
    severity := 'info'; object := 'conf_app';
    problem := format('runs with JIT on: permission checks are many small subplans, and JIT can take longer to compile a read than to run it (hundreds of ms): ALTER ROLE %s SET jit = off', 'conf_app');
    RETURN NEXT;
  END IF;
  -- relations named like a type
  FOR r IN SELECT * FROM (VALUES ('project', 'service', 'relation project.service'), ('note', 'project', 'relation note.project')) v(type, rel, loc)
           WHERE type IS NOT NULL LOOP
    severity := 'info'; object := r.type || '.' || r.rel;
    problem := format('is named like the type %s (%s), so in rules it reads like the type: a name that says what the relation is (author, member) reads better', r.rel, coalesce((SELECT l.loc FROM authz_gen.policy_lines l WHERE l.what = r.loc), '?'));
    RETURN NEXT;
  END LOOP;
  severity := 'info'; object := 'service';
  problem := 'signs in, but has no manage_keys permission, so nobody can make API keys for it: add can manage_keys = ... (' || coalesce((SELECT l.loc FROM authz_gen.policy_lines l WHERE l.what = 'type service'), '?') || ')';
  RETURN NEXT;
  -- columns that move a row under another, with nothing checking where it moves to
  FOR r IN SELECT * FROM (VALUES (NULL::text, NULL::text, NULL::text, NULL::text)) v(tbl, col, rel, loc)
           WHERE tbl IS NOT NULL LOOP
    IF has_column_privilege(v_role, r.tbl, r.col, 'UPDATE') THEN
      severity := 'warning'; object := to_regclass(r.tbl)::text || '.' || r.col;
      problem := format('moves a row under another (%s, %s), and nothing checks where it moves to, so anyone who may update a row may put it inside something they may not change: add a rule such as "update %s after : %s.edit"', r.rel, coalesce((SELECT l.loc FROM authz_gen.policy_lines l WHERE l.what = r.loc), '?'), r.col, r.rel);
      RETURN NEXT;
    END IF;
  END LOOP;
  -- views over governed tables that run with their owner's rights
  FOR r IN SELECT DISTINCT v.oid::regclass AS view, d.refobjid::regclass AS tbl
           FROM pg_depend d JOIN pg_rewrite w ON w.oid = d.objid JOIN pg_class v ON v.oid = w.ev_class
           LEFT JOIN pg_description ds ON ds.objoid = v.oid AND ds.classoid = 'pg_class'::regclass
           WHERE d.classid = 'pg_rewrite'::regclass AND d.refclassid = 'pg_class'::regclass
             AND d.refobjid = ANY (SELECT to_regclass(x) FROM unnest(ARRAY['"app"."inbox"', '"app"."notes"', '"app"."projects"', '"app"."services"', '"app"."users"', '"app"."members"', '"app"."project_services"']::text[]) x)
             AND v.oid <> d.refobjid AND v.relkind IN ('v', 'm')
             AND v.relnamespace NOT IN (to_regnamespace('authz_gen'), to_regnamespace('authz_int'))
             AND coalesce(ds.description, '') <> 'authzc masked view'
             AND NOT coalesce(v.reloptions @> ARRAY['security_invoker=true'], false)
             AND NOT coalesce(v.reloptions @> ARRAY['security_invoker=on'], false)
             AND has_table_privilege(v_role, v.oid, 'SELECT') LOOP
    severity := 'error'; object := r.view::text;
    problem := format('%s may read this view of %s, and views run with their owner''s rights, so row-level security does not apply: ALTER VIEW %s SET (security_invoker = on)', 'conf_app', r.tbl, r.view);
    RETURN NEXT;
  END LOOP;
  -- functions that read governed tables as their owner
  FOR r IN SELECT p.oid::regprocedure AS fn FROM pg_proc p
           WHERE p.prosecdef AND p.pronamespace NOT IN (to_regnamespace('authz'), to_regnamespace('authz_int'),
                                                       to_regnamespace('authz_gen'), 'pg_catalog'::regnamespace)
             AND has_function_privilege(v_role, p.oid, 'EXECUTE')
             AND p.prokind IN ('f', 'p')
             AND EXISTS (SELECT 1 FROM unnest(ARRAY['app.inbox', 'app.notes', 'app.projects', 'app.services', 'app.users', 'app.members', 'app.project_services']::text[]) x
                         WHERE lower(replace(pg_get_functiondef(p.oid), '"', '')) ~
                               ('(from|join|update|into|table|only)\s+(' || lower(split_part(x, '.', 1)) || '\.)?'
                                || lower(split_part(x, '.', 2)) || '([^a-z0-9_$]|$)')) LOOP
    severity := 'warning'; object := r.fn::text;
    problem := 'SECURITY DEFINER, callable by the app role, and seems to use a governed table: it reads rows without row-level security unless its owner is subject to it';
    RETURN NEXT;
  END LOOP;
  -- lookups the permission views make
  FOR r IN SELECT * FROM (VALUES ('"app"."projects"', 'owner_id', 'project.owner: find objects by owner_id'), ('"app"."members"', 'project_id', 'project.member: find the members of an object'), ('"app"."members"', 'user_id', 'project.member: find what a subject is in'), ('"app"."project_services"', 'project_id', 'project.service: find the members of an object'), ('"app"."project_services"', 'service_id', 'project.service: find what a subject is in'), ('"app"."notes"', 'project_id', 'note.project: find objects by project_id'), ('"app"."notes"', 'author_id', 'note.author: find objects by author_id'), ('"app"."inbox"', 'recipient_id', 'message.recipient: find objects by recipient_id')) v(tbl, col, why) WHERE tbl IS NOT NULL LOOP
    CONTINUE WHEN to_regclass(r.tbl) IS NULL;
    -- a plain view can't have an index: the tables under it answer the lookups
    CONTINUE WHEN (SELECT c.relkind FROM pg_class c WHERE c.oid = to_regclass(r.tbl)) = 'v';
    -- an index whose first columns are these (one, or a composite key's, in any order)
    IF NOT EXISTS (SELECT 1 FROM pg_index i
                   WHERE i.indrelid = to_regclass(r.tbl)
                     AND (SELECT array_agg(a.attname::text ORDER BY a.attname)
                          FROM unnest((i.indkey::int2[])[0:cardinality(string_to_array(r.col, ', ')) - 1]) k
                          JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = k)
                         = (SELECT array_agg(c ORDER BY c) FROM unnest(string_to_array(r.col, ', ')) c)) THEN
      severity := 'performance'; object := to_regclass(r.tbl)::text || '.' || r.col;
      problem := format('no index starts with %s (%s): CREATE INDEX ON %s (%s)',
                        CASE WHEN r.col LIKE '%, %' THEN 'these columns' ELSE 'this column' END, r.why, to_regclass(r.tbl),
                        (SELECT string_agg(quote_ident(c), ', ') FROM unnest(string_to_array(r.col, ', ')) c));
      RETURN NEXT;
    END IF;
  END LOOP;
  -- JIT compiles big RLS reads (a list of many rows) for ~0.5 s each time
  IF current_setting('jit') = 'on' AND NOT EXISTS (
       SELECT 1 FROM pg_db_role_setting s, unnest(s.setconfig) c
       WHERE s.setrole = v_role AND c IN ('jit=off', 'jit=false', 'jit=0')) THEN
    severity := 'performance'; object := 'conf_app';
    problem := format('JIT is on: reads that scan many rows through row-level security can spend about half a second compiling. ALTER ROLE %s SET jit = off', 'conf_app');
    RETURN NEXT;
  END IF;
END $f$;

-- Access for roles other than conf_app (e.g. from an earlier policy) is removed
DO $r$
DECLARE g record;
BEGIN
  FOR g IN SELECT DISTINCT a.grantee FROM pg_proc p, aclexplode(p.proacl) a
           WHERE p.pronamespace = 'authz'::regnamespace AND a.grantee NOT IN (p.proowner, 'conf_app'::regrole) LOOP
    EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA authz FROM %s',
                   CASE WHEN g.grantee = 0 THEN 'PUBLIC' ELSE g.grantee::regrole::text END);
  END LOOP;
  FOR g IN SELECT DISTINCT a.grantee FROM pg_namespace n, aclexplode(n.nspacl) a
           WHERE n.nspname = 'authz' AND a.grantee NOT IN (n.nspowner, 'conf_app'::regrole) LOOP
    EXECUTE format('REVOKE ALL ON SCHEMA authz FROM %s',
                   CASE WHEN g.grantee = 0 THEN 'PUBLIC' ELSE g.grantee::regrole::text END);
  END LOOP;
END $r$;

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA authz FROM PUBLIC;

GRANT USAGE ON SCHEMA authz, authz_gen TO conf_app;

GRANT SELECT ON ALL TABLES IN SCHEMA authz_gen TO conf_app;

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA authz_gen FROM PUBLIC;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA authz_gen TO conf_app;

GRANT EXECUTE ON FUNCTION
  authz.uid(),
  authz.principal(),
  authz.ctx(text),
  authz.link_hashes(),
  authz.act_as(text, text),
  authz.connection_check(),
  authz.can(text, text, text),
  authz.list(text, text, text, integer),
  authz.perms(text, text),
  authz.perms_of(text, text[]),
  authz.share(text, text, text, text, text, text, timestamptz, timestamptz, text, jsonb),
  authz.share(text, bigint, text, text, bigint, text, timestamptz, timestamptz, text, jsonb),
  authz.share(text, bigint, text, text, text, text, timestamptz, timestamptz, text, jsonb),
  authz.unshare(text, text, text, text, text, text),
  authz.unshare(text, bigint, text, text, bigint, text),
  authz.unshare(text, bigint, text, text, text, text),
  authz.create_link(text, text, text, timestamptz),
  authz.create_link(text, bigint, text, timestamptz),
  authz.create_role(text, text, text, text, text[]),
  authz.create_role(text, bigint, text, text, text[]),
  authz.set_role_permissions(bigint, text[]),
  authz.delete_role(bigint),
  authz.roles_of(text, text),
  authz.who(text, text, text),
  authz.explain(text, text, text, text),
  authz.list_shares(text, text),
  authz.explain_rule(text, text, text, jsonb),
  authz.who_among(text, text, text, text[], text),
  authz.create_api_key(text, text, timestamptz, text, text),
  authz.list_api_keys(text, text),
  authz.revoke_api_key(bigint),
  authz.login_key(text),
  authz.login_jwt(text),
  authz.view_as(text, text),
  authz.request_access(text, text, text, text, interval),
  authz.request_access(text, bigint, text, text, interval),
  authz.pending_requests(),
  authz.decide_request(bigint, boolean, text),
  authz.cancel_request(bigint),
  authz.break_glass(text, text, text, text, interval),
  authz.start_review(text, text, timestamptz),
  authz.review_items(bigint),
  authz.review_decide(bigint, integer, boolean),
  authz.close_review(bigint, boolean),
  authz.who(text, bigint, text),
  authz.explain(text, bigint, text, text),
  authz.list_shares(text, bigint),
  authz.can(text, bigint, text),
  authz.who_among(text, bigint, text, text[], text),
  authz.perms(text, bigint)
  TO conf_app;

-- the policy now in force
INSERT INTO authz.policy_versions (action, policy, files, version, lock)
VALUES ('apply', $authz_policy$-- The conformance app's policy: projects with an owner and members, public ones anyone may read, a service
-- that reads the projects it is added to, notes in projects, and an inbox only its recipient reads.

role conf_app

type user = app.users

type service = app.services principal

type project = app.projects
  owner   : user    = owner_id
  member  : user    = app.members(project_id -> user_id)
  service : service = app.project_services(project_id -> service_id)

  can edit = owner or member
  can view = edit or service or {public}

type note = app.notes
  project : project = project_id
  author  : user    = author_id

  can edit = author or project.owner
  can view = project.view

type message = app.inbox
  recipient : user = recipient_id

  can read = recipient

rules app.projects
  select : view

rules app.notes
  select : view
  insert : project.edit and {author_id = authz.uid()}
  update : edit
  delete : edit

rules app.inbox
  select : read
  insert : signed_in and {sender_id = authz.uid()}
$authz_policy$,
  $authz_files${}$authz_files$::jsonb, '0.1.0-dev+fdf6725c2fa7', '0cdb17d8dd525729');
