"""rowfence: authz canonical share ids

Revision ID: 7004d579386a
Revises: dcbb4b913e4b
Create Date: 2026-09-30 16:39:45

Generated by rowfence migrate from the policy: the SQL is in 7004d579386a_authz_canonical_share_ids.sql, beside this file. Don't edit
either; change the policy and run rowfence migrate again.
"""
from pathlib import Path

from alembic import op

revision = "7004d579386a"
down_revision: str | None = 'dcbb4b913e4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    sql = Path(__file__).with_suffix(".sql").read_text(encoding="utf-8")
    # as one script, straight to the driver: the SQL has % signs and colons, which are not parameters
    op.get_bind().exec_driver_sql(sql, execution_options={"no_parameters": True})


def downgrade() -> None:
    raise NotImplementedError("a rowfence migration isn't undone: change the policy back and write a new one")
