"""rowfence: authz principals are rows

Revision ID: 77642127e84e
Revises: aa06ea51402d
Create Date: 2026-10-01 10:33:14

Generated by rowfence migrate from the policy: the SQL is in 77642127e84e_authz_principals_are_rows.sql, beside this file. Don't edit
either; change the policy and run rowfence migrate again.
"""
from pathlib import Path

from alembic import op

revision = "77642127e84e"
down_revision: str | None = 'aa06ea51402d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    sql = Path(__file__).with_suffix(".sql").read_text(encoding="utf-8")
    # as one script, straight to the driver: the SQL has % signs and colons, which are not parameters
    op.get_bind().exec_driver_sql(sql, execution_options={"no_parameters": True})


def downgrade() -> None:
    raise NotImplementedError("a rowfence migration isn't undone: change the policy back and write a new one")
