"""rowfence: authz runtime fixes

Revision ID: 936cbc026568
Revises: 10e3c6952e1d
Create Date: 2026-09-30 23:19:00

Generated by rowfence migrate from the policy: the SQL is in 936cbc026568_authz_runtime_fixes.sql, beside this file. Don't edit
either; change the policy and run rowfence migrate again.
"""
from pathlib import Path

from alembic import op

revision = "936cbc026568"
down_revision: str | None = '10e3c6952e1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    sql = Path(__file__).with_suffix(".sql").read_text(encoding="utf-8")
    # as one script, straight to the driver: the SQL has % signs and colons, which are not parameters
    op.get_bind().exec_driver_sql(sql, execution_options={"no_parameters": True})


def downgrade() -> None:
    raise NotImplementedError("a rowfence migration isn't undone: change the policy back and write a new one")
