"""rowfence: authz policy

Revision ID: a1ab017fffc6
Revises: 0001
Create Date: 2026-09-27 21:01:30

Generated by rowfence migrate from the policy: the SQL is in a1ab017fffc6_authz_policy.sql, beside this file. Don't edit
either; change the policy and run rowfence migrate again.
"""
from pathlib import Path

from alembic import op

revision = "a1ab017fffc6"
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    sql = Path(__file__).with_suffix(".sql").read_text(encoding="utf-8")
    # as one script, straight to the driver: the SQL has % signs and colons, which are not parameters
    op.get_bind().exec_driver_sql(sql, execution_options={"no_parameters": True})


def downgrade() -> None:
    raise NotImplementedError("a rowfence migration isn't undone: change the policy back and write a new one")
