"""rowfence: authz star shares

Revision ID: aa06ea51402d
Revises: f8ca18de572f
Create Date: 2026-10-01 07:13:28

Generated by rowfence migrate from the policy: the SQL is in aa06ea51402d_authz_star_shares.sql, beside this file. Don't edit
either; change the policy and run rowfence migrate again.
"""
from pathlib import Path

from alembic import op

revision = "aa06ea51402d"
down_revision: str | None = 'f8ca18de572f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    sql = Path(__file__).with_suffix(".sql").read_text(encoding="utf-8")
    # as one script, straight to the driver: the SQL has % signs and colons, which are not parameters
    op.get_bind().exec_driver_sql(sql, execution_options={"no_parameters": True})


def downgrade() -> None:
    raise NotImplementedError("a rowfence migration isn't undone: change the policy back and write a new one")
