"""rowfence: authz catalog privileges

Revision ID: b0faed2f5b4f
Revises: 59976a20bb15
Create Date: 2026-09-30 20:40:30

Generated by rowfence migrate from the policy: the SQL is in b0faed2f5b4f_authz_catalog_privileges.sql, beside this file. Don't edit
either; change the policy and run rowfence migrate again.
"""
from pathlib import Path

from alembic import op

revision = "b0faed2f5b4f"
down_revision: str | None = '59976a20bb15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    sql = Path(__file__).with_suffix(".sql").read_text(encoding="utf-8")
    # as one script, straight to the driver: the SQL has % signs and colons, which are not parameters
    op.get_bind().exec_driver_sql(sql, execution_options={"no_parameters": True})


def downgrade() -> None:
    raise NotImplementedError("a rowfence migration isn't undone: change the policy back and write a new one")
