"""rowfence: authz trees in batches

Revision ID: b786a2d632e8
Revises: 9e3424271558
Create Date: 2026-10-03 07:15:27

Generated by rowfence migrate from the policy: the SQL is in b786a2d632e8_authz_trees_in_batches.sql, beside this file. Don't edit
either; change the policy and run rowfence migrate again.
"""
from pathlib import Path

from alembic import op

revision = "b786a2d632e8"
down_revision: str | None = '9e3424271558'
branch_labels = None
depends_on = None


def upgrade() -> None:
    sql = Path(__file__).with_suffix(".sql").read_text(encoding="utf-8")
    # as one script, straight to the driver: the SQL has % signs and colons, which are not parameters
    op.get_bind().exec_driver_sql(sql, execution_options={"no_parameters": True})


def downgrade() -> None:
    raise NotImplementedError("a rowfence migration isn't undone: change the policy back and write a new one")
