"""rowfence: authz roles from owner

Revision ID: f8ca18de572f
Revises: 936cbc026568
Create Date: 2026-10-01 05:49:11

Generated by rowfence migrate from the policy: the SQL is in f8ca18de572f_authz_roles_from_owner.sql, beside this file. Don't edit
either; change the policy and run rowfence migrate again.
"""
from pathlib import Path

from alembic import op

revision = "f8ca18de572f"
down_revision: str | None = '936cbc026568'
branch_labels = None
depends_on = None


def upgrade() -> None:
    sql = Path(__file__).with_suffix(".sql").read_text(encoding="utf-8")
    # as one script, straight to the driver: the SQL has % signs and colons, which are not parameters
    op.get_bind().exec_driver_sql(sql, execution_options={"no_parameters": True})


def downgrade() -> None:
    raise NotImplementedError("a rowfence migration isn't undone: change the policy back and write a new one")
