-- rowfence 0.1.0-dev: canonical_share_ids. Generated by rowfence migrate from the policy; don't edit it,
-- change the policy and write the next migration.
-- the same policy; what rowfence makes of it changed

SELECT pg_catalog.set_config('lock_timeout', '10s', true) WHERE pg_catalog.current_setting('lock_timeout') IN ('0', '0ms');
SELECT pg_catalog.set_config('check_function_bodies', 'off', true);

-- this migration starts from the policy the previous one left
DO $authz_guard$
DECLARE v_lock text;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_catalog.pg_attribute
             WHERE attrelid = to_regclass('authz.policy_versions') AND attname = 'lock' AND NOT attisdropped) THEN
    EXECUTE 'SELECT lock FROM authz.policy_versions ORDER BY id DESC LIMIT 1' INTO v_lock;
  END IF;
  IF v_lock IS DISTINCT FROM 'e7b82b805b16a82a' THEN
    RAISE EXCEPTION 'rowfence: this migration changes the policy the migration before it left (%), but the database has % [AZ607]',
      'e7b82b805b16a82a', coalesce(v_lock, 'none')
      USING HINT = 'apply the migrations in order; a database changed with rowfence push or apply since needs the '
                   'migrations from the start (or rowfence apply of the policy the previous migration left)';
  END IF;
END $authz_guard$;

-- Functions below resolve names with the search_path in effect now, temporary schema last
DO $sp$ BEGIN PERFORM pg_catalog.set_config('search_path', pg_catalog.concat_ws(', ',
  nullif(pg_catalog.current_setting('search_path'), ''), 'pg_temp'), true); END $sp$;

-- shares written directly get canonical ids too
CREATE FUNCTION authz_int.shares_canon() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, pg_temp AS $f$
BEGIN
  NEW.object_id := authz_int.canon(NEW.object_type, NEW.object_id);
  NEW.subject_id := authz_int.canon(NEW.subject_type, NEW.subject_id);
  RETURN NEW;
END $f$;

CREATE TRIGGER authz_shares_canon BEFORE INSERT OR UPDATE OF object_type, object_id, subject_type, subject_id
  ON authz.shares FOR EACH ROW EXECUTE FUNCTION authz_int.shares_canon();

DO $r$ BEGIN PERFORM set_config('authz_ctx.reason', 'applying the policy: the row was deleted', true); END $r$;

-- Shares stored with ids that aren't canonical ('007', an uppercase uuid: written directly before every
-- write went through authz_int.canon) are made canonical, since the sweep below and the triggers compare
-- text; one that then repeats a share already stored goes, the first made staying
CREATE TEMP TABLE authz_uncanonical ON COMMIT DROP AS
  SELECT g.ctid AS row, authz_int.canon(g.object_type, g.object_id) AS object_id,
         authz_int.canon(g.subject_type, g.subject_id) AS subject_id
  FROM authz.shares g
  WHERE g.object_id IS DISTINCT FROM authz_int.canon(g.object_type, g.object_id)
     OR g.subject_id IS DISTINCT FROM authz_int.canon(g.subject_type, g.subject_id);
DELETE FROM authz.shares g USING authz_uncanonical u
WHERE g.ctid = u.row AND EXISTS (
  SELECT 1 FROM authz.shares c WHERE c.object_type = g.object_type AND c.object_id = u.object_id AND c.relation = g.relation
    AND c.subject_type = g.subject_type AND c.subject_id = u.subject_id AND c.subject_relation = g.subject_relation);
DELETE FROM authz.shares g USING (
  SELECT u.row, row_number() OVER (PARTITION BY s.object_type, u.object_id, s.relation, s.subject_type, u.subject_id,
                                   s.subject_relation ORDER BY s.created_at, u.row) AS n
  FROM authz_uncanonical u JOIN authz.shares s ON s.ctid = u.row) d
WHERE g.ctid = d.row AND d.n > 1;
UPDATE authz.shares g SET object_id = u.object_id, subject_id = u.subject_id FROM authz_uncanonical u WHERE g.ctid = u.row;
DROP TABLE authz_uncanonical;

-- Shares on rows that no longer exist (deleted while no trigger watched them) are dropped
DELETE FROM authz.shares g WHERE g.object_type = 'user' AND NOT EXISTS (SELECT 1 FROM "fm"."users" x WHERE x."id"::text = g.object_id);
DELETE FROM authz.shares g WHERE g.subject_type = 'user' AND NOT EXISTS (SELECT 1 FROM "fm"."users" x WHERE x."id"::text = g.subject_id);
DELETE FROM authz.shares g WHERE g.object_type = 'group' AND NOT EXISTS (SELECT 1 FROM "fm"."groups" x WHERE x."id"::text = g.object_id);
DELETE FROM authz.shares g WHERE g.subject_type = 'group' AND NOT EXISTS (SELECT 1 FROM "fm"."groups" x WHERE x."id"::text = g.subject_id);
DELETE FROM authz.shares g WHERE g.object_type = 'membership' AND NOT EXISTS (SELECT 1 FROM "fm"."group_members" x WHERE x."id"::text = g.object_id);
DELETE FROM authz.shares g WHERE g.subject_type = 'membership' AND NOT EXISTS (SELECT 1 FROM "fm"."group_members" x WHERE x."id"::text = g.subject_id);
DELETE FROM authz.shares g WHERE g.object_type = 'folder' AND NOT EXISTS (SELECT 1 FROM "fm"."folders" x WHERE x."id"::text = g.object_id);
DELETE FROM authz.shares g WHERE g.subject_type = 'folder' AND NOT EXISTS (SELECT 1 FROM "fm"."folders" x WHERE x."id"::text = g.subject_id);
DELETE FROM authz.shares g WHERE g.object_type = 'file' AND NOT EXISTS (SELECT 1 FROM "fm"."files" x WHERE x."id"::text = g.object_id);
DELETE FROM authz.shares g WHERE g.subject_type = 'file' AND NOT EXISTS (SELECT 1 FROM "fm"."files" x WHERE x."id"::text = g.subject_id);
DELETE FROM authz.shares g WHERE g.object_type = 'version' AND NOT EXISTS (SELECT 1 FROM "fm"."file_versions" x WHERE x."id"::text = g.object_id);
DELETE FROM authz.shares g WHERE g.subject_type = 'version' AND NOT EXISTS (SELECT 1 FROM "fm"."file_versions" x WHERE x."id"::text = g.subject_id);

DO $r$ BEGIN PERFORM set_config('authz_ctx.reason', '', true); END $r$;

-- Access for roles other than fm_app (e.g. from an earlier policy) is removed
DO $r$
DECLARE g record;
BEGIN
  FOR g IN SELECT DISTINCT a.grantee FROM pg_proc p, aclexplode(p.proacl) a
           WHERE p.pronamespace = 'authz'::regnamespace AND a.grantee NOT IN (p.proowner, 'fm_app'::regrole) LOOP
    EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA authz FROM %s',
                   CASE WHEN g.grantee = 0 THEN 'PUBLIC' ELSE g.grantee::regrole::text END);
  END LOOP;
  FOR g IN SELECT DISTINCT a.grantee FROM pg_namespace n, aclexplode(n.nspacl) a
           WHERE n.nspname = 'authz' AND a.grantee NOT IN (n.nspowner, 'fm_app'::regrole) LOOP
    EXECUTE format('REVOKE ALL ON SCHEMA authz FROM %s',
                   CASE WHEN g.grantee = 0 THEN 'PUBLIC' ELSE g.grantee::regrole::text END);
  END LOOP;
END $r$;

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA authz FROM PUBLIC;

GRANT USAGE ON SCHEMA authz, authz_gen TO fm_app;

GRANT SELECT ON ALL TABLES IN SCHEMA authz_gen TO fm_app;

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA authz_gen FROM PUBLIC;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA authz_gen TO fm_app;

GRANT EXECUTE ON FUNCTION
  authz.uid(),
  authz.principal(),
  authz.ctx(text),
  authz.link_hashes(),
  authz.act_as(text, text),
  authz.connection_check(),
  authz.can(text, text, text),
  authz.list(text, text, text, integer),
  authz.perms(text, text),
  authz.perms_of(text, text[]),
  authz.share(text, text, text, text, text, text, timestamptz, timestamptz, text, jsonb),
  authz.share(text, bigint, text, text, bigint, text, timestamptz, timestamptz, text, jsonb),
  authz.share(text, bigint, text, text, text, text, timestamptz, timestamptz, text, jsonb),
  authz.unshare(text, text, text, text, text, text),
  authz.unshare(text, bigint, text, text, bigint, text),
  authz.unshare(text, bigint, text, text, text, text),
  authz.create_link(text, text, text, timestamptz),
  authz.create_link(text, bigint, text, timestamptz),
  authz.create_role(text, text, text, text, text[]),
  authz.create_role(text, bigint, text, text, text[]),
  authz.set_role_permissions(bigint, text[]),
  authz.delete_role(bigint),
  authz.roles_of(text, text),
  authz.who(text, text, text),
  authz.explain(text, text, text, text),
  authz.list_shares(text, text),
  authz.explain_rule(text, text, text, jsonb),
  authz.who_among(text, text, text, text[], text),
  authz.create_api_key(text, text, timestamptz, text, text),
  authz.list_api_keys(text, text),
  authz.revoke_api_key(bigint),
  authz.login_key(text),
  authz.login_jwt(text),
  authz.view_as(text, text),
  authz.request_access(text, text, text, text, interval),
  authz.request_access(text, bigint, text, text, interval),
  authz.pending_requests(),
  authz.decide_request(bigint, boolean, text),
  authz.cancel_request(bigint),
  authz.break_glass(text, text, text, text, interval),
  authz.start_review(text, text, timestamptz),
  authz.review_items(bigint),
  authz.review_decide(bigint, integer, boolean),
  authz.close_review(bigint, boolean),
  authz.who(text, bigint, text),
  authz.explain(text, bigint, text, text),
  authz.list_shares(text, bigint),
  authz.who(text, uuid, text),
  authz.explain(text, uuid, text, text),
  authz.list_shares(text, uuid),
  authz.can(text, bigint, text),
  authz.can(text, uuid, text),
  authz.who_among(text, bigint, text, text[], text),
  authz.who_among(text, uuid, text, text[], text),
  authz.perms(text, bigint),
  authz.perms(text, uuid)
  TO fm_app;

-- the policy now in force
INSERT INTO authz.policy_versions (action, policy, files, version, lock)
VALUES ('apply', $authz_policy$-- policy.authz: who can do what in the file manager. Applied by db/migrate.py with authz.apply().
-- Folders nest; what you may do in a folder you may do in everything inside it, unless a folder
-- stops inheritance (inherit = false). People share folders and files with users and groups.

role fm_app

type user = fm.users (id uuid)

type group = fm.groups (id uuid)
  member : user         = fm.group_members(group_id -> user_id)
  member : group#member = fm.groups(parent_id -> id)          -- members of sub-groups count too
  owner  : user         = owner_id
  admin  : user         = fm.group_members(group_id -> user_id) where {is_admin}
  parent : group        = parent_id

  -- who may rename it, add and remove members and sub-groups: its owner, its admins, and those of the groups above
  can manage = owner or admin or parent.manage

type membership = fm.group_members
  group : group = group_id
  person : user = user_id

  can manage = group.manage

type folder = fm.folders
  parent : folder = parent_id
  owner  : user   = owner_id
  viewer : user, group#member, link shared by share
  editor : user, group#member       shared by share

  can share = owner or (parent.share and {inherit})
  can edit  = share or editor or (parent.edit and {inherit})
  can view  = edit or viewer or (parent.view and {inherit})
  -- support staff may give themselves access for a short time: audited, announced (authz.break_glass)
  can break_glass = {exists (select 1 from fm.users u where u.id = authz.uid() and u.is_support)}

type file = fm.files
  folder : folder = folder_id
  owner  : user   = owner_id
  viewer : user, group#member, link shared by share
  editor : user, group#member       shared by share

  can share = owner or folder.share
  can edit  = share or editor or folder.edit
  can view  = edit or viewer or folder.view

-- every stored object is a version of a file, with the file's permissions
type version = fm.file_versions
  file : file = file_id

  can view = file.view
  can edit = file.edit

rules fm.folders
  select                 : view
  insert                 : ({parent_id is null} or parent.edit) and {owner_id = authz.uid()}
  update                 : edit
  update parent_id after : parent.edit or ({parent_id is null} and share)
  update id, owner_id, inherit : share
  delete                 : share

rules fm.files
  select                 : view
  insert                 : folder.edit and {owner_id = authz.uid()} and {fm.key_is_new(object_key)}
  update                 : edit
  update folder_id after : folder.edit
  update id, owner_id    : share
  -- a file shows one of its own versions, never another file's object
  update object_key after : {object_key IN (SELECT v.object_key FROM fm.file_versions v WHERE v.file_id = files.id AND v.ready)}
  delete                 : edit

rules fm.file_versions
  select                 : view
  insert                 : file.edit and {created_by = authz.uid()}
  update                 : edit
  update id, file_id, object_key, created_by : {false}             -- what a version is never changes
  delete                 : edit

-- everyone signed in sees the groups and who is in them (to share with them)
rules fm.groups
  select                 : signed_in
  insert                 : {owner_id = authz.uid()} and ({parent_id is null} or parent.manage)
  update                 : manage
  update parent_id after : {parent_id is null} or parent.manage
  update id, owner_id    : manage
  delete                 : manage

rules fm.group_members
  select                 : signed_in
  insert                 : manage
  update                 : manage
  update group_id after  : manage
  delete                 : manage or person                    -- anyone may leave a group
$authz_policy$,
  $authz_files${}$authz_files$::jsonb, '0.1.0-dev+ae5fccdf9a9b', '0c72af059907ba61');
