-- =====================================================================
-- app_schema.sql — an example app that already exists, with its data.
-- Nothing here knows about permissions: the policy file maps onto it.
-- =====================================================================
\set ON_ERROR_STOP on
SET client_min_messages = warning;

DROP SCHEMA IF EXISTS authz_gen, authz_int, authz, test, bench, app CASCADE;
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user NOLOGIN;   -- the role your application connects as
  END IF;
END $$;

CREATE SCHEMA app;

CREATE TABLE app.users (
  id   bigint PRIMARY KEY,
  name text NOT NULL
);
CREATE TABLE app.orgs (
  id   bigint PRIMARY KEY,
  name text NOT NULL
);
CREATE TABLE app.org_members (
  org_id  bigint NOT NULL REFERENCES app.orgs,
  user_id bigint NOT NULL REFERENCES app.users,
  role    text   NOT NULL CHECK (role IN ('admin', 'member')),
  PRIMARY KEY (org_id, user_id)
);
CREATE INDEX ON app.org_members (user_id);
CREATE TABLE app.teams (
  id        bigint PRIMARY KEY,
  org_id    bigint NOT NULL REFERENCES app.orgs,
  parent_id bigint REFERENCES app.teams,       -- sub-teams
  name      text   NOT NULL
);
CREATE INDEX ON app.teams (parent_id);
CREATE TABLE app.team_members (
  team_id bigint NOT NULL REFERENCES app.teams,
  user_id bigint NOT NULL REFERENCES app.users,
  PRIMARY KEY (team_id, user_id)
);
CREATE INDEX ON app.team_members (user_id);
CREATE TABLE app.folders (
  id        bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id    bigint  NOT NULL REFERENCES app.orgs,
  parent_id bigint  REFERENCES app.folders ON UPDATE CASCADE,   -- delete contents first
  owner_id  bigint  REFERENCES app.users,
  name      text    NOT NULL,
  inherit   boolean NOT NULL DEFAULT true
);
CREATE INDEX ON app.folders (parent_id);
CREATE INDEX ON app.folders (owner_id);
CREATE INDEX ON app.folders (org_id);
CREATE TABLE app.files (
  id           bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folder_id    bigint  NOT NULL REFERENCES app.folders ON UPDATE CASCADE,
  owner_id     bigint  REFERENCES app.users,
  name         text    NOT NULL,
  confidential boolean NOT NULL DEFAULT false,
  body         text
);
CREATE INDEX ON app.files (folder_id);
CREATE INDEX ON app.files (owner_id);
-- the app already lets admins give a whole team access to a folder
CREATE TABLE app.folder_team_access (
  folder_id bigint NOT NULL REFERENCES app.folders ON DELETE CASCADE ON UPDATE CASCADE,
  team_id   bigint NOT NULL REFERENCES app.teams,
  access    text   NOT NULL CHECK (access IN ('view', 'edit')),
  PRIMARY KEY (folder_id, team_id)
);
CREATE INDEX ON app.folder_team_access (team_id);
-- a folder can also appear inside other folders (like a shortcut)
CREATE TABLE app.folder_links (
  folder_id bigint NOT NULL REFERENCES app.folders ON DELETE CASCADE ON UPDATE CASCADE,
  parent_id bigint NOT NULL REFERENCES app.folders ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (folder_id, parent_id)
);
CREATE INDEX ON app.folder_links (parent_id);

GRANT USAGE ON SCHEMA app TO app_user;
GRANT SELECT ON ALL TABLES IN SCHEMA app TO app_user;
GRANT INSERT, UPDATE, DELETE ON app.folders, app.files TO app_user;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA app TO app_user;

-- ---------------------------------------------------------------------
-- Existing data
--   Acme (org 1): alice, bob, carol are members, erin is an admin
--   Globex (org 2): frank is an admin
--   dave is an outside guest; gina is only in a team
--   Teams: Engineering (alice)
--          └── Backend (bob)
--              └── Platform (gina)
--
--   Company              shared with all Acme members (added via authz.share)
--   ├── Handbook         handbook.pdf, salaries.xlsx (confidential)
--   └── Engineering      owner alice, Engineering team: edit (app table)
--       ├── Design docs  architecture.md
--       └── Secrets      BREAKS INHERITANCE, Backend team: view (app table)
--           │            offer-letter.pdf (shared with dave)
--           └── Keys     prod-keys.txt
--   Globex               globex-plan.md
--   └── Joint project    joint-plan.md, ALSO LINKED INTO Company (app.folder_links)
-- ---------------------------------------------------------------------
INSERT INTO app.users VALUES
  (1, 'alice'), (2, 'bob'), (3, 'carol'), (4, 'dave'), (5, 'erin'), (6, 'frank'), (7, 'gina');
INSERT INTO app.orgs VALUES (1, 'Acme'), (2, 'Globex');
INSERT INTO app.org_members VALUES
  (1, 1, 'member'), (1, 2, 'member'), (1, 3, 'member'), (1, 5, 'admin'), (2, 6, 'admin');
INSERT INTO app.teams VALUES (10, 1, NULL, 'Engineering'), (11, 1, 10, 'Backend'), (12, 1, 11, 'Platform');
INSERT INTO app.team_members VALUES (10, 1), (11, 2), (12, 7);
INSERT INTO app.folders (id, org_id, parent_id, owner_id, name, inherit) VALUES
  (1, 1, NULL, 5, 'Company', true),
  (2, 1, 1, 5, 'Handbook', true),
  (3, 1, 1, 1, 'Engineering', true),
  (4, 1, 3, 1, 'Design docs', true),
  (5, 1, 3, 5, 'Secrets', false),
  (6, 1, 5, 5, 'Keys', true),
  (20, 2, NULL, 6, 'Globex', true),
  (21, 2, 20, 6, 'Joint project', true);
INSERT INTO app.files (id, folder_id, owner_id, name, confidential) VALUES
  (10, 2, 5, 'handbook.pdf', false),
  (11, 4, 1, 'architecture.md', false),
  (12, 6, 5, 'prod-keys.txt', false),
  (13, 5, 5, 'offer-letter.pdf', false),
  (14, 2, 5, 'salaries.xlsx', true),
  (15, 20, 6, 'globex-plan.md', false),
  (16, 21, 6, 'joint-plan.md', false);
INSERT INTO app.folder_team_access VALUES (3, 10, 'edit'), (5, 11, 'view');
INSERT INTO app.folder_links VALUES (21, 1);
DO $$ BEGIN
  PERFORM setval(pg_get_serial_sequence('app.folders', 'id'), 100);
  PERFORM setval(pg_get_serial_sequence('app.files', 'id'), 100);
END $$;
