-- rowstile 0.1.0-dev: one_sqlstate_per_code (1 of 2). Generated by rowstile migrate from the policy; don't edit it,
-- change the policy and write the next migration.
-- builds folder__parent__tree beside the ones in use; the next migration swaps it in

-- a migration is one transaction: outside one, nothing below changes anything
SELECT pg_catalog.set_config('authz_ctx.migration', 'b089d60c8a08e284', true);
DO $authz_tx$
BEGIN
  IF pg_catalog.current_setting('authz_ctx.migration', true) IS DISTINCT FROM 'b089d60c8a08e284' THEN
    PERFORM pg_catalog.set_config('default_transaction_read_only', 'on', false);
  END IF;
END $authz_tx$;
DO $authz_tx$
BEGIN
  IF pg_catalog.current_setting('authz_ctx.migration', true) IS DISTINCT FROM 'b089d60c8a08e284' THEN
    RAISE EXCEPTION 'rowstile: this migration must run in one transaction, and its statements are being committed one by one [AZ615]'
      USING HINT = 'nothing was changed, and this session is read-only from here on; run the file with your migration tool, or with psql -1 -f';
  END IF;
END $authz_tx$;

SELECT pg_catalog.set_config('lock_timeout', '10s', true) WHERE pg_catalog.current_setting('lock_timeout') IN ('0', '0ms');
SELECT pg_catalog.set_config('check_function_bodies', 'off', true);

-- this migration starts from the policy the previous one left
DO $authz_guard$
DECLARE v_lock text;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_catalog.pg_attribute
             WHERE attrelid = to_regclass('authz.policy_versions') AND attname = 'lock' AND NOT attisdropped) THEN
    EXECUTE 'SELECT lock FROM authz.policy_versions ORDER BY id DESC LIMIT 1' INTO v_lock;
  END IF;
  IF v_lock = 'b089d60c8a08e284' THEN
    RAISE EXCEPTION 'rowstile: this database already holds what this migration brings (it ran here before, or rowstile dev or push took the database there): don''t run it, tell your migration tool it is applied [AZ607]'
      USING HINT = 'Prisma: prisma migrate resolve --applied <the migration''s folder>. Alembic: alembic stamp head. '
                   'Others, and why: rowstile help AZ607';
  ELSIF v_lock IS DISTINCT FROM '4f1af069378205a3' THEN
    RAISE EXCEPTION 'rowstile: this migration changes the policy the migration before it left (%), but the database has % [AZ607]',
      '4f1af069378205a3', coalesce(v_lock, 'none')
      USING HINT = 'apply the migrations in order; a database changed with rowstile push or apply since needs the '
                   'migrations from the start (or rowstile apply of the policy the previous migration left) '
                   '(rowstile help AZ607)';
  END IF;
END $authz_guard$;

-- what the trees are built from: this snapshot, then what changed since (the next migration)
CREATE TABLE IF NOT EXISTS authz_int.next_trees (name text PRIMARY KEY, hash text NOT NULL, snap pg_snapshot NOT NULL, feed bigint NOT NULL);

-- folder__parent__tree: built beside the one in use, reading the app's tables only (the app keeps working)
DELETE FROM authz_int.next_trees WHERE name = 'folder__parent__tree';
DROP TABLE IF EXISTS authz_int."folder__parent__tree__next";
DROP FUNCTION IF EXISTS authz_int."folder__parent__tree__next_compute"(p_ids integer[]);
INSERT INTO authz_int.next_trees VALUES ('folder__parent__tree', '4a060eb4d2df88b4eb42d84faa2128d0', pg_catalog.pg_current_snapshot(), (SELECT coalesce(max(pos), 0) FROM authz.changes));
CREATE TABLE authz_int."folder__parent__tree__next" (descendant integer NOT NULL, ancestor integer NOT NULL,
  PRIMARY KEY (descendant, ancestor));
CREATE INDEX ON authz_int."folder__parent__tree__next" (ancestor);
CREATE FUNCTION authz_int."folder__parent__tree__next_compute"(p_ids integer[]) RETURNS TABLE (o_descendant integer, o_ancestor integer)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path FROM CURRENT AS $f$
  WITH RECURSIVE up(_d, _a) AS (
    SELECT x."id", x."id" FROM "app"."folders" x WHERE x."id" = ANY (p_ids)
    UNION
    SELECT up._d, e._parent
    FROM up
    -- one index lookup per step: joined plainly, a small table gets a full scan at every step
    -- (OFFSET 0 keeps the planner from turning this into a hash join)
    CROSS JOIN LATERAL (SELECT c.* FROM "app"."folders" c WHERE c."id" = up._a OFFSET 0) c
    CROSS JOIN LATERAL (
      (SELECT x.* FROM (SELECT 0 AS _link, r."id" AS _child, r."parent_id" AS _parent FROM "app"."folders" r WHERE r."parent_id" IS NOT NULL) x WHERE x._child = up._a OFFSET 0)) e
    WHERE (e._link = 0)
      AND EXISTS (SELECT 1 FROM "app"."folders" p WHERE p."id" = e._parent))
  SELECT _d, _a FROM up
$f$;
DO $authz_build$
DECLARE batch integer[];
BEGIN
  FOR batch IN SELECT array_agg(k.k) FROM (SELECT "id" AS k, row_number() OVER () AS n FROM "app"."folders") k GROUP BY (k.n - 1) / 10000 LOOP
    INSERT INTO authz_int."folder__parent__tree__next" (descendant, ancestor)
    SELECT o_descendant, o_ancestor FROM authz_int."folder__parent__tree__next_compute"(batch);
  END LOOP;
END $authz_build$;

-- the policy in force is the same; the next migration starts from here
UPDATE authz.policy_versions SET lock = 'b089d60c8a08e284' WHERE id = (SELECT max(id) FROM authz.policy_versions);
